import { Question } from './types';

export const PYTHON_LEVEL4_QUESTIONS: Question[] = [
  // --- 基础语法 (101-120) ---
  { id: 101, subject: 'python', type: 'single', title: '在 Python 中，下列哪个变量名是合法的？', options: ['2_variable', '_variable', 'variable-name', 'if'], answer: '_variable', points: 2, explanation: '变量名不能以数字开头，不能包含连字符，不能是关键字。下划线开头是合法的。' },
  { id: 102, subject: 'python', type: 'single', title: '执行 print(type(10)) 的输出结果是？', options: ["<class 'int'>", "<class 'str'>", "<class 'float'>", "<class 'bool'>"], answer: "<class 'int'>", points: 2, explanation: '10 是整数类型。' },
  { id: 103, subject: 'python', type: 'single', title: '执行 print(type("10")) 的输出结果是？', options: ["<class 'int'>", "<class 'str'>", "<class 'float'>", "<class 'bool'>"], answer: "<class 'str'>", points: 2, explanation: '用引号括起来的是字符串类型。' },
  { id: 104, subject: 'python', type: 'single', title: '下列哪个函数可以将字符串 "123" 转换为整数 123？', options: ['str()', 'float()', 'int()', 'bool()'], answer: 'int()', points: 2, explanation: 'int() 函数用于类型转换。' },
  { id: 105, subject: 'python', type: 'single', title: 'input() 函数返回的数据类型默认是？', options: ['int', 'float', 'str', 'list'], answer: 'str', points: 2, explanation: 'input() 接收的所有输入默认为字符串。' },
  { id: 106, subject: 'python', type: 'single', title: '执行 print(10 // 3) 的结果是？', options: ['3.33', '3', '1', '4'], answer: '3', points: 2, explanation: '// 是整除运算符。' },
  { id: 107, subject: 'python', type: 'single', title: '执行 print(2 ** 3) 的结果是？', options: ['6', '8', '9', '5'], answer: '8', points: 2, explanation: '** 是幂运算符，2的3次方是8。' },
  { id: 108, subject: 'python', type: 'single', title: '下列哪个符号用于表示 Python 的多行注释（通常用法）？', options: ['#', '//', "''' 或 \"\"\"", '/* */'], answer: "''' 或 \"\"\"", points: 2, explanation: '三引号可用于多行注释。' },
  { id: 109, subject: 'python', type: 'single', title: '执行 a = 5; b = 2; print(a % b) 的结果是？', options: ['2', '2.5', '1', '0'], answer: '1', points: 2, explanation: '% 是取余运算符。' },
  { id: 110, subject: 'python', type: 'single', title: 'Python 中赋值运算符是？', options: ['==', '=', ':=', 'equals'], answer: '=', points: 2, explanation: '= 是赋值，== 是判断相等。' },
  { id: 111, subject: 'python', type: 'single', title: '执行 print("Python" * 2) 的结果是？', options: ['PythonPython', 'Python 2', '报错', 'Python*2'], answer: 'PythonPython', points: 2, explanation: '字符串乘以数字表示重复。' },
  { id: 112, subject: 'python', type: 'single', title: '下列哪个不是 Python 的关键字？', options: ['if', 'while', 'print', 'for'], answer: 'print', points: 2, explanation: 'print 是内置函数，不是关键字（在 Python 3 中）。' },
  { id: 113, subject: 'python', type: 'single', title: '执行 a = "10"; b = 5; print(int(a) + b) 的结果是？', options: ['105', '15', '报错', '10+5'], answer: '15', points: 2, explanation: '先转换类型再相加。' },
  { id: 114, subject: 'python', type: 'single', title: 'Python 3 中，print(5 / 2) 的结果是？', options: ['2', '2.5', '2.0', '3'], answer: '2.5', points: 2, explanation: '/ 是浮点除法。' },
  { id: 115, subject: 'python', type: 'single', title: '变量名可以以数字开头吗？', options: ['可以', '不可以', '只有 0 可以', '视情况而定'], answer: '不可以', points: 2, explanation: '变量名必须以字母或下划线开头。' },
  { id: 116, subject: 'python', type: 'single', title: '执行 print(str(123) + "45") 的结果是？', options: ['168', '12345', '报错', '123+45'], answer: '12345', points: 2, explanation: '数字转字符串后进行拼接。' },
  { id: 117, subject: 'python', type: 'single', title: 'Python 中布尔类型的两个值是？', options: ['yes / no', 'T / F', 'True / False', '1 / 0'], answer: 'True / False', points: 2, explanation: '注意首字母大写。' },
  { id: 118, subject: 'python', type: 'single', title: '执行 a = 10; a += 5; print(a) 的结果是？', options: ['5', '10', '15', '报错'], answer: '15', points: 2, explanation: 'a += 5 等同于 a = a + 5。' },
  { id: 119, subject: 'python', type: 'single', title: '下列哪个运算符的优先级最高？', options: ['+', '*', '**', '('], answer: '(', points: 2, explanation: '括号优先级最高。' },
  { id: 120, subject: 'python', type: 'single', title: '在 Python 中，如何在一行输出多个内容并用逗号分隔？', options: ['print(a, b)', 'print(a + b)', 'print(a; b)', 'print(a and b)'], answer: 'print(a, b)', points: 2, explanation: 'print 函数支持多个参数。' },

  // --- 判断与逻辑 (121-140) ---
  { id: 121, subject: 'python', type: 'single', title: '下列哪个是 Python 中的“不等于”运算符？', options: ['<>', '!=', '==!', 'not='], answer: '!=', points: 2, explanation: '!= 表示不等于。' },
  { id: 122, subject: 'python', type: 'single', title: '执行 print(5 > 3 and 2 > 4) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: 'and 要求两边都为真，2 > 4 为假。' },
  { id: 123, subject: 'python', type: 'single', title: '执行 print(5 > 3 or 2 > 4) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'or 只要有一边为真即为真。' },
  { id: 124, subject: 'python', type: 'single', title: '执行 print(not 5 > 3) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: 'not 取反，5 > 3 是 True，取反是 False。' },
  { id: 125, subject: 'python', type: 'single', title: 'Python 中 if 语句后面的条件判断之后必须加什么符号？', options: [';', ':', '.', ','], answer: ':', points: 2, explanation: 'if、elif、else 后面都要加冒号。' },
  { id: 126, subject: 'python', type: 'single', title: 'Python 中依靠什么来区分代码块？', options: ['大括号 {}', '小括号 ()', '缩进', '分号 ;'], answer: '缩进', points: 2, explanation: '缩进是 Python 的灵魂。' },
  { id: 127, subject: 'python', type: 'single', title: '下列代码的输出是？\na = 10\nif a > 5:\n    print("A")\nelse:\n    print("B")', options: ['A', 'B', 'AB', '报错'], answer: 'A', points: 2, explanation: '10 > 5 为真，执行 if 分支。' },
  { id: 128, subject: 'python', type: 'single', title: '下列代码的输出是？\nscore = 85\nif score >= 90:\n    print("优")\nelif score >= 80:\n    print("良")\nelse:\n    print("及格")', options: ['优', '良', '及格', '报错'], answer: '良', points: 2, explanation: '85 满足 score >= 80。' },
  { id: 129, subject: 'python', type: 'single', title: '判断一个数 n 是否为偶数的条件表达式是？', options: ['n % 2 == 0', 'n / 2 == 0', 'n % 2 == 1', 'n // 2 == 0'], answer: 'n % 2 == 0', points: 2, explanation: '偶数除以 2 余数为 0。' },
  { id: 130, subject: 'python', type: 'single', title: '执行 print(10 == "10") 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: '整数和字符串不相等。' },
  { id: 131, subject: 'python', type: 'single', title: '下列哪个逻辑运算符具有短路特性？', options: ['and', 'or', 'and 和 or', 'not'], answer: 'and 和 or', points: 2, explanation: 'and 和 or 都会根据第一个操作数决定是否计算第二个。' },
  { id: 132, subject: 'python', type: 'single', title: 'if 语句中，如果 if 条件不满足，想接着判断另一个条件，应该用？', options: ['else', 'elif', 'if again', 'other'], answer: 'elif', points: 2, explanation: 'elif 是 else if 的缩写。' },
  { id: 133, subject: 'python', type: 'single', title: '下列代码运行结果是？\nx = 5\nif x > 2:\n    if x < 10:\n        print(1)\n    else:\n        print(2)\nelse:\n    print(3)', options: ['1', '2', '3', '报错'], answer: '1', points: 2, explanation: '嵌套判断。' },
  { id: 134, subject: 'python', type: 'single', title: '判断变量 x 是否在 1 到 10 之间（包含 1 和 10）的正确写法是？', options: ['1 <= x <= 10', 'x >= 1 and x <= 10', 'A 和 B 都对', 'x in range(1, 10)'], answer: 'A 和 B 都对', points: 2, explanation: 'Python 支持链式比较。' },
  { id: 135, subject: 'python', type: 'single', title: '执行 print(bool(0)) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: '数字 0 的布尔值是 False。' },
  { id: 136, subject: 'python', type: 'single', title: '执行 print(bool("False")) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '非空字符串的布尔值是 True。' },
  { id: 137, subject: 'python', type: 'single', title: '下列代码输出什么？\na = True\nb = False\nprint(a or b and b)', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'and 优先级高于 or，先算 b and b 为 False，再算 a or False 为 True。' },
  { id: 138, subject: 'python', type: 'single', title: 'Python 中判断“不属于”的关键字是？', options: ['not in', 'is not', '!=', 'not'], answer: 'not in', points: 2, explanation: '用于判断元素不在容器中。' },
  { id: 139, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 10\ny = 20\nif x < y:\n    x, y = y, x\nprint(x)', options: ['10', '20', '报错', 'None'], answer: '20', points: 2, explanation: '交换了 x 和 y 的值。' },
  { id: 140, subject: 'python', type: 'single', title: '在 if 语句中，else 分支是必须的吗？', options: ['是', '不是', '只有在有 elif 时才是', '视 Python 版本而定'], answer: '不是', points: 2, explanation: 'else 是可选的。' },

  // --- 循环 (141-150) ---
  { id: 141, subject: 'python', type: 'single', title: 'range(5) 生成的序列是？', options: ['1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '0, 1, 2, 3, 4, 5', '1, 2, 3, 4'], answer: '0, 1, 2, 3, 4', points: 2, explanation: 'range(n) 从 0 开始到 n-1。' },
  { id: 142, subject: 'python', type: 'single', title: 'range(1, 10, 2) 生成的序列是？', options: ['1, 3, 5, 7, 9', '1, 2, 3, 4, 5, 6, 7, 8, 9', '2, 4, 6, 8', '1, 3, 5, 7'], answer: '1, 3, 5, 7, 9', points: 2, explanation: '起点 1，终点 10（不含），步长 2。' },
  { id: 143, subject: 'python', type: 'single', title: '下列代码的输出结果是？\nfor i in range(3):\n    print(i, end="")', options: ['012', '123', '0123', '报错'], answer: '012', points: 2, explanation: '循环三次，打印 0, 1, 2。' },
  { id: 144, subject: 'python', type: 'single', title: '在循环中，用于跳出整个循环的关键字是？', options: ['continue', 'break', 'exit', 'stop'], answer: 'break', points: 2, explanation: 'break 终止当前循环。' },
  { id: 145, subject: 'python', type: 'single', title: '在循环中，用于跳过本次循环剩余代码、直接进入下一次循环的关键字是？', options: ['continue', 'break', 'pass', 'next'], answer: 'continue', points: 2, explanation: 'continue 结束本次迭代。' },
  { id: 146, subject: 'python', type: 'single', title: '下列代码执行后，sum 的值是？\nsum = 0\nfor i in range(1, 6):\n    sum += i', options: ['10', '15', '21', '5'], answer: '15', points: 2, explanation: '1+2+3+4+5 = 15。' },
  { id: 147, subject: 'python', type: 'single', title: 'while 循环执行的条件是？', options: ['条件为真', '条件为假', '执行一次后停止', '无限循环'], answer: '条件为真', points: 2, explanation: 'while 条件: 只要条件为真就一直执行。' },
  { id: 148, subject: 'python', type: 'single', title: '下列代码会打印几次 "Hi"？\ni = 0\nwhile i < 3:\n    print("Hi")\n    i += 1', options: ['2', '3', '4', '无数次'], answer: '3', points: 2, explanation: 'i 分别为 0, 1, 2 时满足条件。' },
  { id: 149, subject: 'python', type: 'single', title: '下列代码的输出是？\nfor i in range(5):\n    if i == 2:\n        break\n    print(i, end="")', options: ['01', '012', '01234', '2'], answer: '01', points: 2, explanation: '当 i 等于 2 时循环终止。' },
  { id: 150, subject: 'python', type: 'single', title: '下列代码的输出是？\nfor i in range(3):\n    if i == 1:\n        continue\n    print(i, end="")', options: ['012', '02', '1', '0'], answer: '02', points: 2, explanation: '跳过了 i 等于 1 的那次打印。' },

  // --- 循环 (续) & 字符串与列表 (151-175) ---
  { id: 151, subject: 'python', type: 'single', title: '下列代码运行结果是？\nfor i in range(1, 1):\n    print("Hi")', options: ['打印一次 Hi', '不打印', '报错', '无限打印'], answer: '不打印', points: 2, explanation: 'range(1, 1) 生成的是空序列。' },
  { id: 152, subject: 'python', type: 'single', title: '如何获取字符串 s = "Hello" 的长度？', options: ['s.length()', 'len(s)', 'size(s)', 'count(s)'], answer: 'len(s)', points: 2, explanation: 'len() 函数用于获取容器长度。' },
  { id: 153, subject: 'python', type: 'single', title: '字符串 s = "Python"，s[1] 的值是？', options: ['P', 'y', 't', 'h'], answer: 'y', points: 2, explanation: '索引从 0 开始，s[0] 是 P，s[1] 是 y。' },
  { id: 154, subject: 'python', type: 'single', title: '字符串 s = "abc"，执行 s + "de" 的结果是？', options: ['abcde', 'abc de', '报错', 'abc+de'], answer: 'abcde', points: 2, explanation: '字符串拼接。' },
  { id: 155, subject: 'python', type: 'single', title: '列表 a = [1, 2, 3]，执行 a.append(4) 后，a 的值是？', options: ['[4, 1, 2, 3]', '[1, 2, 3, 4]', '[1, 2, 3]', '[5]'], answer: '[1, 2, 3, 4]', points: 2, explanation: 'append() 在列表末尾添加元素。' },
  { id: 156, subject: 'python', type: 'single', title: '列表 a = [10, 20, 30]，执行 a[0] = 100 后，a 的值是？', options: ['[100, 20, 30]', '[10, 20, 30, 100]', '[100]', '报错'], answer: '[100, 20, 30]', points: 2, explanation: '列表是可变的，可以通过索引修改元素。' },
  { id: 157, subject: 'python', type: 'single', title: '下列哪个操作可以删除列表 a = [1, 2, 3] 中的最后一个元素？', options: ['a.remove(3)', 'a.pop()', 'del a[-1]', '以上都可以'], answer: '以上都可以', points: 2, explanation: '多种方式可以删除元素。' },
  { id: 158, subject: 'python', type: 'single', title: '执行 print("a" in "apple") 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'in 运算符检查子串是否存在。' },
  { id: 159, subject: 'python', type: 'single', title: '列表 a = [1, 2]，执行 a * 2 的结果是？', options: ['[2, 4]', '[1, 2, 1, 2]', '[1, 2, 2]', '报错'], answer: '[1, 2, 1, 2]', points: 2, explanation: '列表乘以数字表示重复。' },
  { id: 160, subject: 'python', type: 'single', title: '如何遍历列表 my_list 中的每一个元素 x？', options: ['for x in my_list:', 'while x in my_list:', 'for i from 0 to len(my_list):', 'my_list.foreach(x)'], answer: 'for x in my_list:', points: 2, explanation: 'for...in... 是遍历列表的标准写法。' },
  { id: 161, subject: 'python', type: 'single', title: '字符串 s = "12345"，s[-1] 的值是？', options: ['1', '5', '4', '报错'], answer: '5', points: 2, explanation: '负数索引从末尾开始，-1 是最后一个。' },
  { id: 162, subject: 'python', type: 'single', title: '执行 print("Hello".lower()) 的结果是？', options: ['HELLO', 'hello', 'Hello', 'h'], answer: 'hello', points: 2, explanation: 'lower() 转小写。' },
  { id: 163, subject: 'python', type: 'single', title: '执行 print("apple".count("p")) 的结果是？', options: ['1', '2', '0', '报错'], answer: '2', points: 2, explanation: 'count() 统计子串出现次数。' },
  { id: 164, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(len(a))', options: ['2', '3', '4', '报错'], answer: '3', points: 2, explanation: '列表长度为 3。' },
  { id: 165, subject: 'python', type: 'single', title: '如何清空列表 a？', options: ['a.clear()', 'a = []', 'del a[:]', '以上都可以'], answer: '以上都可以', points: 2, explanation: '多种方式清空列表。' },
  { id: 166, subject: 'python', type: 'single', title: '执行 print("a,b,c".split(",")) 的结果是？', options: ["['a', 'b', 'c']", "('a', 'b', 'c')", "'abc'", "报错"], answer: "['a', 'b', 'c']", points: 2, explanation: 'split() 根据分隔符切分字符串。' },
  { id: 167, subject: 'python', type: 'single', title: '执行 print("-".join(["a", "b"])) 的结果是？', options: ['a-b', 'ab-', '-ab', '报错'], answer: 'a-b', points: 2, explanation: 'join() 将序列连接成字符串。' },
  { id: 168, subject: 'python', type: 'single', title: '列表 a = [1, 5, 2]，执行 a.sort() 后，a 的值是？', options: ['[1, 5, 2]', '[1, 2, 5]', '[5, 2, 1]', '[2, 1, 5]'], answer: '[1, 2, 5]', points: 2, explanation: 'sort() 对列表进行升序排序。' },
  { id: 169, subject: 'python', type: 'single', title: '执行 print("Python"[0:2]) 的结果是？', options: ['Py', 'Pyt', 'y', 'Python'], answer: 'Py', points: 2, explanation: '切片 [start:end] 不含 end。' },
  { id: 170, subject: 'python', type: 'single', title: '下列哪个不是字符串的方法？', options: ['upper()', 'append()', 'replace()', 'find()'], answer: 'append()', points: 2, explanation: 'append() 是列表的方法。' },
  { id: 171, subject: 'python', type: 'single', title: '执行 print("123".isdigit()) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'isdigit() 检查字符串是否全为数字。' },
  { id: 172, subject: 'python', type: 'single', title: '列表 a = [1, 2, 3]，执行 a.insert(1, 4) 后，a 的值是？', options: ['[4, 1, 2, 3]', '[1, 4, 2, 3]', '[1, 2, 4, 3]', '[1, 4, 3]'], answer: '[1, 4, 2, 3]', points: 2, explanation: 'insert(index, obj) 在指定位置插入。' },
  { id: 173, subject: 'python', type: 'single', title: '执行 print(list(range(3))) 的结果是？', options: ['[0, 1, 2]', '[1, 2, 3]', '[0, 1, 2, 3]', '报错'], answer: '[0, 1, 2]', points: 2, explanation: 'range 转列表。' },
  { id: 174, subject: 'python', type: 'single', title: '下列代码输出什么？\ns = "abcde"\nprint(s[::2])', options: ['ace', 'bd', 'abcde', '报错'], answer: 'ace', points: 2, explanation: '切片步长为 2。' },
  { id: 175, subject: 'python', type: 'single', title: '如何判断列表 a 是否为空？', options: ['if not a:', 'if len(a) == 0:', 'if a == []:', '以上都可以'], answer: '以上都可以', points: 2, explanation: '多种判断空列表的方式。' },

  // --- 函数 (176-190) ---
  { id: 176, subject: 'python', type: 'single', title: 'Python 中定义函数的关键字是？', options: ['function', 'def', 'func', 'define'], answer: 'def', points: 2, explanation: 'def 关键字用于定义函数。' },
  { id: 177, subject: 'python', type: 'single', title: '函数定义中，括号里的变量被称为？', options: ['参数', '返回值', '局部变量', '全局变量'], answer: '参数', points: 2, explanation: '参数用于接收外部传入的数据。' },
  { id: 178, subject: 'python', type: 'single', title: '函数执行完毕后，向调用者传回结果的关键字是？', options: ['get', 'give', 'return', 'back'], answer: 'return', points: 2, explanation: 'return 语句用于返回结果并结束函数。' },
  { id: 179, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef add(a, b):\n    return a + b\nprint(add(3, 4))', options: ['7', '34', '报错', 'None'], answer: '7', points: 2, explanation: '函数调用并返回和。' },
  { id: 180, subject: 'python', type: 'single', title: '如果一个函数没有 return 语句，它默认返回？', options: ['0', 'False', 'None', '报错'], answer: 'None', points: 2, explanation: 'Python 函数默认返回 None。' },
  { id: 181, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef say_hi(name="Guest"):\n    print("Hi " + name)\nsay_hi()', options: ['Hi Guest', 'Hi', '报错', 'None'], answer: 'Hi Guest', points: 2, explanation: '使用了默认参数。' },
  { id: 182, subject: 'python', type: 'single', title: '在函数内部定义的变量被称为？', options: ['全局变量', '局部变量', '静态变量', '私有变量'], answer: '局部变量', points: 2, explanation: '作用域仅限于函数内部。' },
  { id: 183, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 10\ndef change():\n    x = 20\nchange()\nprint(x)', options: ['10', '20', '报错', 'None'], answer: '10', points: 2, explanation: '函数内部的 x 是局部变量，不影响外部全局变量。' },
  { id: 184, subject: 'python', type: 'single', title: '想在函数内部修改全局变量，需要使用哪个关键字？', options: ['global', 'extern', 'public', 'outer'], answer: 'global', points: 2, explanation: 'global 声明变量为全局变量。' },
  { id: 185, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef func(n):\n    if n == 1:\n        return 1\n    return n * func(n-1)\nprint(func(3))', options: ['3', '6', '9', '报错'], answer: '6', points: 2, explanation: '递归计算阶乘，3*2*1=6。' },
  { id: 186, subject: 'python', type: 'single', title: '下列哪个是 Python 的内置函数？', options: ['print()', 'input()', 'len()', '以上都是'], answer: '以上都是', points: 2, explanation: '这些都是 Python 自带的常用函数。' },
  { id: 187, subject: 'python', type: 'single', title: '函数可以有多个返回值吗？', options: ['可以（以元组形式）', '不可以', '只能有一个数字', '只能有一个字符串'], answer: '可以（以元组形式）', points: 2, explanation: 'Python 支持 return a, b 这种写法。' },
  { id: 188, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef test(a, b=10):\n    return a + b\nprint(test(5))', options: ['5', '10', '15', '报错'], answer: '15', points: 2, explanation: '使用了默认参数 b=10。' },
  { id: 189, subject: 'python', type: 'single', title: '调用函数时，参数传递的顺序必须和定义时一致吗？', options: ['必须一致', '不一定（可以使用关键字参数）', '只能按顺序', '视情况而定'], answer: '不一定（可以使用关键字参数）', points: 2, explanation: '可以使用 key=value 形式传参。' },
  { id: 190, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef double(x):\n    return x * 2\nprint(double(double(2)))', options: ['4', '8', '16', '报错'], answer: '8', points: 2, explanation: '嵌套调用，double(2)=4, double(4)=8。' },

  // --- 简单算法与综合 (191-200) ---
  { id: 191, subject: 'python', type: 'single', title: '判断闰年的条件是？', options: ['能被4整除且不能被100整除', '能被400整除', 'A 或 B', '能被4整除'], answer: 'A 或 B', points: 2, explanation: '闰年判定规则。' },
  { id: 192, subject: 'python', type: 'single', title: '下列代码用于求 1-100 之间所有偶数的和，空白处应填？\ns = 0\nfor i in range(1, 101):\n    if ______:\n        s += i', options: ['i % 2 == 0', 'i % 2 != 0', 'i / 2 == 0', 'i // 2 == 0'], answer: 'i % 2 == 0', points: 2, explanation: '偶数判定。' },
  { id: 193, subject: 'python', type: 'single', title: '质数（素数）是指？', options: ['只能被1和它本身整除的大于1的自然数', '所有的奇数', '能被2整除的数', '能被3整除的数'], answer: '只能被1和它本身整除的大于1的自然数', points: 2, explanation: '质数定义。' },
  { id: 194, subject: 'python', type: 'single', title: '下列代码输出什么？\ns = "level"\nprint(s == s[::-1])', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '判断回文字符串。' },
  { id: 195, subject: 'python', type: 'single', title: '九九乘法表中，第 3 行第 2 列的结果是？', options: ['5', '6', '9', '12'], answer: '6', points: 2, explanation: '3 * 2 = 6。' },
  { id: 196, subject: 'python', type: 'single', title: '下列代码执行后，a 的值是？\na = 10\nb = 20\na = a + b\nb = a - b\na = a - b', options: ['a=10, b=20', 'a=20, b=10', 'a=30, b=10', '报错'], answer: 'a=20, b=10', points: 2, explanation: '不使用中间变量交换两个数。' },
  { id: 197, subject: 'python', type: 'single', title: '下列代码输出什么？\nfor i in range(1, 4):\n    for j in range(1, 3):\n        if i == j:\n            print(i, end="")', options: ['12', '123', '1122', '报错'], answer: '12', points: 2, explanation: '双重循环，当 i 等于 j 时打印。' },
  { id: 198, subject: 'python', type: 'single', title: '在 Python 中，如何产生一个 1-10 之间的随机整数？', options: ['random.randint(1, 10)', 'random.random(1, 10)', 'random.range(1, 10)', 'randint(1, 10)'], answer: 'random.randint(1, 10)', points: 2, explanation: '使用 random 模块的 randint 函数。' },
  { id: 199, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(len(a))', options: ['3', '4', '报错', 'None'], answer: '4', points: 2, explanation: '列表是引用传递，b 和 a 指向同一个对象。' },
  { id: 200, subject: 'python', type: 'single', title: 'YCL 4 级考试中，编程题通常要求？', options: ['只写出思路', '写出完整的、可运行的代码', '只需要选择正确答案', '口头描述过程'], answer: '写出完整的、可运行的代码', points: 2, explanation: '编程题考察实际动手能力。' },

  // --- 综合强化 (201-250) ---
  { id: 201, subject: 'python', type: 'single', title: '下列哪个符号用于表示 Python 的整除？', options: ['/', '//', '%', '\\'], answer: '//', points: 2, explanation: '// 是整除运算符。' },
  { id: 202, subject: 'python', type: 'single', title: '执行 print(bool("")) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: '空字符串的布尔值为 False。' },
  { id: 203, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2]\nb = [3, 4]\nprint(a + b)', options: ['[1, 2, 3, 4]', '[4, 6]', '[[1, 2], [3, 4]]', '报错'], answer: '[1, 2, 3, 4]', points: 2, explanation: '列表相加表示合并。' },
  { id: 204, subject: 'python', type: 'single', title: '如何获取列表 a 的最后一个元素？', options: ['a[len(a)]', 'a[-1]', 'a[last]', 'a.end()'], answer: 'a[-1]', points: 2, explanation: '-1 索引指向最后一个元素。' },
  { id: 205, subject: 'python', type: 'single', title: '执行 print("abc".upper()) 的结果是？', options: ['abc', 'ABC', 'Abc', '报错'], answer: 'ABC', points: 2, explanation: 'upper() 转大写。' },
  { id: 206, subject: 'python', type: 'single', title: '下列代码输出什么？\nfor i in range(1, 5, 2):\n    print(i, end="")', options: ['1234', '13', '135', '24'], answer: '13', points: 2, explanation: '起点1，终点5（不含），步长2。' },
  { id: 207, subject: 'python', type: 'single', title: 'Python 中，如何定义一个空字典？', options: ['d = []', 'd = {}', 'd = ()', 'd = ""'], answer: 'd = {}', points: 2, explanation: '花括号用于定义字典。' },
  { id: 208, subject: 'python', type: 'single', title: '执行 print(round(3.6)) 的结果是？', options: ['3', '4', '3.0', '4.0'], answer: '4', points: 2, explanation: 'round() 进行四舍五入。' },
  { id: 209, subject: 'python', type: 'single', title: '下列代码输出什么？\ns = "Python"\nprint(s[2:4])', options: ['yt', 'th', 'ytho', 'py'], answer: 'th', points: 2, explanation: '索引2是t，索引3是h，不含索引4。' },
  { id: 210, subject: 'python', type: 'single', title: '在 Python 中，None 表示？', options: ['0', 'False', '空值', '报错'], answer: '空值', points: 2, explanation: 'None 是一个特殊的常量，表示空。' },
  { id: 211, subject: 'python', type: 'single', title: '执行 print(min(5, 2, 8)) 的结果是？', options: ['5', '2', '8', '报错'], answer: '2', points: 2, explanation: 'min() 返回最小值。' },
  { id: 212, subject: 'python', type: 'single', title: '下列哪个操作可以向列表 a 的末尾添加元素 10？', options: ['a.add(10)', 'a.append(10)', 'a.push(10)', 'a.insert(10)'], answer: 'a.append(10)', points: 2, explanation: 'append() 是标准添加方法。' },
  { id: 213, subject: 'python', type: 'single', title: '执行 print(abs(-5)) 的结果是？', options: ['5', '-5', '0', '报错'], answer: '5', points: 2, explanation: 'abs() 返回绝对值。' },
  { id: 214, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 5\nx *= 2 + 3\nprint(x)', options: ['13', '25', '10', '报错'], answer: '25', points: 2, explanation: '先算 2+3=5，再算 5*5=25。' },
  { id: 215, subject: 'python', type: 'single', title: '如何将字符串 "3.14" 转换为浮点数？', options: ['int()', 'float()', 'str()', 'bool()'], answer: 'float()', points: 2, explanation: 'float() 用于转换浮点数。' },
  { id: 216, subject: 'python', type: 'single', title: '执行 print("apple".find("e")) 的结果是？', options: ['4', '5', '-1', '报错'], answer: '4', points: 2, explanation: 'e 的索引是 4。' },
  { id: 217, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(a.pop(1))', options: ['1', '2', '3', '[1, 3]'], answer: '2', points: 2, explanation: 'pop(1) 弹出索引为 1 的元素。' },
  { id: 218, subject: 'python', type: 'single', title: 'Python 中，布尔值 True 对应的整数值是？', options: ['0', '1', '-1', '任意正数'], answer: '1', points: 2, explanation: 'True 在数值运算中当作 1。' },
  { id: 219, subject: 'python', type: 'single', title: '执行 print(10 / 2 == 5) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '5.0 等于 5。' },
  { id: 220, subject: 'python', type: 'single', title: '下列代码输出什么？\nfor i in range(1, 3):\n    print("A", end="")\nelse:\n    print("B", end="")', options: ['AB', 'AAB', 'AA', 'B'], answer: 'AAB', points: 2, explanation: '循环正常结束后执行 else 分支。' },
  { id: 221, subject: 'python', type: 'single', title: '如何判断一个字符串 s 是否以 "Py" 开头？', options: ['s.startswith("Py")', 's.beginwith("Py")', 's[0:2] == "Py"', 'A 和 C 都对'], answer: 'A 和 C 都对', points: 2, explanation: '多种方式判断开头。' },
  { id: 222, subject: 'python', type: 'single', title: '执行 print(pow(2, 3)) 的结果是？', options: ['6', '8', '9', '报错'], answer: '8', points: 2, explanation: 'pow(x, y) 等同于 x ** y。' },
  { id: 223, subject: 'python', type: 'single', title: '下列哪个函数可以对列表进行永久性排序？', options: ['sorted()', 'sort()', 'order()', 'arrange()'], answer: 'sort()', points: 2, explanation: 'sort() 修改原列表，sorted() 返回新列表。' },
  { id: 224, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\ndel a[1]\nprint(a)', options: ['[1, 2, 3]', '[1, 3]', '[2, 3]', '报错'], answer: '[1, 3]', points: 2, explanation: '删除了索引为 1 的元素。' },
  { id: 225, subject: 'python', type: 'single', title: '执行 print("abc" * 0) 的结果是？', options: ['abc', '0', '空字符串', '报错'], answer: '空字符串', points: 2, explanation: '重复 0 次得到空串。' },
  { id: 226, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 10\nif x > 5:\n    pass\nelse:\n    print("Hi")', options: ['Hi', '什么都不输出', '报错', 'None'], answer: '什么都不输出', points: 2, explanation: 'pass 是空语句，占位用。' },
  { id: 227, subject: 'python', type: 'single', title: '如何获取字典 d 中键 "name" 对应的值？', options: ['d["name"]', 'd.get("name")', 'A 和 B 都对', 'd.name'], answer: 'A 和 B 都对', points: 2, explanation: '字典取值的常用方式。' },
  { id: 228, subject: 'python', type: 'single', title: '执行 print(len([1, [2, 3]])) 的结果是？', options: ['2', '3', '1', '报错'], answer: '2', points: 2, explanation: '外层列表有两个元素：1 和 [2, 3]。' },
  { id: 229, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef func(x):\n    return x + 1\nprint(func(func(1)))', options: ['1', '2', '3', '报错'], answer: '3', points: 2, explanation: '嵌套调用。' },
  { id: 230, subject: 'python', type: 'single', title: 'Python 中，如何表示“无穷大”？', options: ['inf', 'float("inf")', 'max', '1/0'], answer: 'float("inf")', points: 2, explanation: '浮点数形式表示无穷大。' },
  { id: 231, subject: 'python', type: 'single', title: '执行 print("Hello World".replace(" ", "")) 的结果是？', options: ['HelloWorld', 'Hello World', 'Hello-World', '报错'], answer: 'HelloWorld', points: 2, explanation: '将空格替换为空。' },
  { id: 232, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(a[::-1])', options: ['[1, 2, 3]', '[3, 2, 1]', '[1]', '报错'], answer: '[3, 2, 1]', points: 2, explanation: '列表反转切片。' },
  { id: 233, subject: 'python', type: 'single', title: '如何判断一个数 n 是否能被 3 和 5 同时整除？', options: ['n % 3 == 0 and n % 5 == 0', 'n % 15 == 0', 'A 和 B 都对', 'n % 3 == 0 or n % 5 == 0'], answer: 'A 和 B 都对', points: 2, explanation: '逻辑判断。' },
  { id: 234, subject: 'python', type: 'single', title: '执行 print(chr(97)) 的结果是？', options: ['a', 'A', '97', '报错'], answer: 'a', points: 2, explanation: 'chr() 返回 ASCII 码对应的字符。' },
  { id: 235, subject: 'python', type: 'single', title: '执行 print(ord("a")) 的结果是？', options: ['97', '65', 'a', '报错'], answer: '97', points: 2, explanation: 'ord() 返回字符对应的 ASCII 码。' },
  { id: 236, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = [1, 2]\nx.extend([3, 4])\nprint(len(x))', options: ['2', '3', '4', '报错'], answer: '4', points: 2, explanation: 'extend() 合并列表。' },
  { id: 237, subject: 'python', type: 'single', title: '如何将列表 a 转换为字符串，元素间用逗号分隔？', options: ['",".join(a)', 'str(a)', 'a.to_string()', 'join(a, ",")'], answer: '",".join(a)', points: 2, explanation: '前提是列表元素都是字符串。' },
  { id: 238, subject: 'python', type: 'single', title: '执行 print(sum([1, 2, 3])) 的结果是？', options: ['6', '123', '报错', 'None'], answer: '6', points: 2, explanation: 'sum() 对序列求和。' },
  { id: 239, subject: 'python', type: 'single', title: '下列代码输出什么？\na = 10\ndef func():\n    a = 20\nfunc()\nprint(a)', options: ['10', '20', '报错', 'None'], answer: '10', points: 2, explanation: '局部变量不影响全局。' },
  { id: 240, subject: 'python', type: 'single', title: 'Python 中，如何导入 math 模块？', options: ['import math', 'include math', 'using math', 'require math'], answer: 'import math', points: 2, explanation: '使用 import 关键字。' },
  { id: 241, subject: 'python', type: 'single', title: '执行 print(math.sqrt(16)) 的结果是？', options: ['4', '4.0', '8', '报错'], answer: '4.0', points: 2, explanation: 'sqrt() 返回浮点数。' },
  { id: 242, subject: 'python', type: 'single', title: '下列代码输出什么？\nfor i in range(1, 4):\n    if i == 2:\n        continue\n    print(i, end="")', options: ['123', '13', '1', '3'], answer: '13', points: 2, explanation: '跳过 i=2。' },
  { id: 243, subject: 'python', type: 'single', title: '如何获取字符串 s 的最后三个字符？', options: ['s[-3:]', 's[3:]', 's[:-3]', 's[0:3]'], answer: 's[-3:]', points: 2, explanation: '切片用法。' },
  { id: 244, subject: 'python', type: 'single', title: '执行 print("Python".find("z")) 的结果是？', options: ['0', '-1', '报错', 'None'], answer: '-1', points: 2, explanation: '找不到子串返回 -1。' },
  { id: 245, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2]\na.append([3, 4])\nprint(len(a))', options: ['2', '3', '4', '报错'], answer: '3', points: 2, explanation: 'append 了一个列表作为单个元素。' },
  { id: 246, subject: 'python', type: 'single', title: '如何判断一个数 n 是否为质数？', options: ['检查 2 到 n-1 之间是否有数能整除 n', '检查 n 是否为奇数', '检查 n 是否大于 1', 'A 和 C'], answer: 'A 和 C', points: 2, explanation: '质数判定逻辑。' },
  { id: 247, subject: 'python', type: 'single', title: '执行 print(10 // 3.0) 的结果是？', options: ['3', '3.0', '1', '1.0'], answer: '3.0', points: 2, explanation: '整除运算如果有浮点数参与，结果为浮点数。' },
  { id: 248, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 1\nwhile x < 5:\n    x += 2\nprint(x)', options: ['3', '5', '7', '报错'], answer: '5', points: 2, explanation: '1->3->5，5不满足条件停止。' },
  { id: 249, subject: 'python', type: 'single', title: '在 Python 中，如何定义一个元组？', options: ['t = [1, 2]', 't = (1, 2)', 't = {1, 2}', 't = "1, 2"'], answer: 't = (1, 2)', points: 2, explanation: '小括号用于定义元组。' },
  { id: 250, subject: 'python', type: 'single', title: '元组和列表的主要区别是？', options: ['元组不可变，列表可变', '元组可变，列表不可变', '元组只能存数字', '列表只能存字符串'], answer: '元组不可变，列表可变', points: 2, explanation: '元组是不可变序列。' },

  // --- 考前冲刺 (251-300) ---
  { id: 251, subject: 'python', type: 'single', title: '执行 print(type(range(5))) 的结果是？', options: ["<class 'list'>", "<class 'range'>", "<class 'tuple'>", "<class 'int'>"], answer: "<class 'range'>", points: 2, explanation: 'range 返回的是一个 range 对象。' },
  { id: 252, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef func(a, b=5):\n    return a * b\nprint(func(2, 3))', options: ['10', '6', '15', '报错'], answer: '6', points: 2, explanation: '传入了参数 b=3，覆盖了默认值 5。' },
  { id: 253, subject: 'python', type: 'single', title: '如何将字符串 "Hello" 反转？', options: ['"Hello".reverse()', '"Hello"[::-1]', 'reverse("Hello")', 'A 和 B'], answer: '"Hello"[::-1]', points: 2, explanation: '切片反转是最常用的方式。' },
  { id: 254, subject: 'python', type: 'single', title: '执行 print(10 / 2) 的结果类型是？', options: ['int', 'float', 'str', 'bool'], answer: 'float', points: 2, explanation: 'Python 3 中 / 总是返回浮点数。' },
  { id: 255, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nb = a.copy()\nb[0] = 100\nprint(a[0])', options: ['1', '100', '报错', 'None'], answer: '1', points: 2, explanation: 'copy() 创建了新对象，修改 b 不影响 a。' },
  { id: 256, subject: 'python', type: 'single', title: '执行 print(bool(None)) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: 'None 的布尔值为 False。' },
  { id: 257, subject: 'python', type: 'single', title: '下列哪个函数可以获取字符的 Unicode 编码？', options: ['chr()', 'ord()', 'unicode()', 'code()'], answer: 'ord()', points: 2, explanation: 'ord() 返回编码。' },
  { id: 258, subject: 'python', type: 'single', title: '执行 print(3 > 2 > 1) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'Python 支持链式比较。' },
  { id: 259, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = "123"\nprint(x * 2)', options: ['246', '123123', '报错', '123*2'], answer: '123123', points: 2, explanation: '字符串重复。' },
  { id: 260, subject: 'python', type: 'single', title: '如何向字典 d 中添加一个键值对 "age": 10？', options: ['d.add("age", 10)', 'd["age"] = 10', 'd.append("age": 10)', 'd.insert("age", 10)'], answer: 'd["age"] = 10', points: 2, explanation: '字典赋值操作。' },
  { id: 261, subject: 'python', type: 'single', title: '执行 print(abs(-10.5)) 的结果是？', options: ['10', '10.5', '-10.5', '11'], answer: '10.5', points: 2, explanation: '绝对值。' },
  { id: 262, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(a[1:1])', options: ['[2]', '[]', '[1, 2]', '报错'], answer: '[]', points: 2, explanation: '切片范围为空。' },
  { id: 263, subject: 'python', type: 'single', title: '如何判断一个字符串 s 是否全由字母组成？', options: ['s.isalpha()', 's.isdigit()', 's.isletter()', 's.islower()'], answer: 's.isalpha()', points: 2, explanation: 'isalpha() 检查字母。' },
  { id: 264, subject: 'python', type: 'single', title: '执行 print(round(3.14159, 2)) 的结果是？', options: ['3.1', '3.14', '3.15', '3'], answer: '3.14', points: 2, explanation: '保留两位小数。' },
  { id: 265, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef func():\n    global x\n    x = 10\nfunc()\nprint(x)', options: ['10', '报错', 'None', '什么都不输出'], answer: '10', points: 2, explanation: '使用 global 声明了全局变量。' },
  { id: 266, subject: 'python', type: 'single', title: 'Python 中，如何获取当前脚本接收的命令行参数？', options: ['sys.argv', 'os.args', 'input()', 'args'], answer: 'sys.argv', points: 2, explanation: 'sys 模块的 argv 列表。' },
  { id: 267, subject: 'python', type: 'single', title: '执行 print("apple".count("a")) 的结果是？', options: ['1', '0', '2', '报错'], answer: '1', points: 2, explanation: '计数。' },
  { id: 268, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2]\na.extend("34")\nprint(len(a))', options: ['3', '4', '报错', 'None'], answer: '4', points: 2, explanation: 'extend 迭代字符串 "34"，添加了 "3" 和 "4"。' },
  { id: 269, subject: 'python', type: 'single', title: '如何将列表 ["a", "b"] 合并为字符串 "ab"？', options: ['"".join(["a", "b"])', 'str(["a", "b"])', '["a", "b"].join("")', 'sum(["a", "b"])'], answer: '"".join(["a", "b"])', points: 2, explanation: 'join 方法。' },
  { id: 270, subject: 'python', type: 'single', title: '执行 print(10 % -3) 的结果是？', options: ['1', '-2', '-1', '报错'], answer: '-2', points: 2, explanation: 'Python 的取余运算遵循向下取整原则。' },
  { id: 271, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 5\nif x > 2:\n    print("A", end="")\nif x > 3:\n    print("B", end="")', options: ['A', 'B', 'AB', '报错'], answer: 'AB', points: 2, explanation: '两个独立的 if 语句都会执行。' },
  { id: 272, subject: 'python', type: 'single', title: '如何在一个函数中返回多个值？', options: ['return a, b', 'return [a, b]', 'return (a, b)', '以上都可以'], answer: '以上都可以', points: 2, explanation: 'Python 灵活的返回方式。' },
  { id: 273, subject: 'python', type: 'single', title: '执行 print(max("abc", "abd")) 的结果是？', options: ['abc', 'abd', 'a', '报错'], answer: 'abd', points: 2, explanation: '字符串按字典序比较。' },
  { id: 274, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(a[1:])', options: ['[1, 2]', '[2, 3]', '[1, 2, 3]', '[2]'], answer: '[2, 3]', points: 2, explanation: '从索引 1 到末尾。' },
  { id: 275, subject: 'python', type: 'single', title: '如何判断一个键 k 是否在字典 d 中？', options: ['k in d', 'd.has(k)', 'k in d.keys()', 'A 和 C 都对'], answer: 'A 和 C 都对', points: 2, explanation: '判断键是否存在。' },
  { id: 276, subject: 'python', type: 'single', title: '执行 print(10 // 3) 的结果是？', options: ['3', '3.33', '1', '0'], answer: '3', points: 2, explanation: '整除。' },
  { id: 277, subject: 'python', type: 'single', title: '下列代码输出什么？\ns = "Python"\nprint(s.find("y"))', options: ['0', '1', '2', '报错'], answer: '1', points: 2, explanation: '索引。' },
  { id: 278, subject: 'python', type: 'single', title: '如何将数字 123 转换为字符串？', options: ['str(123)', 'int(123)', 'float(123)', '123.to_string()'], answer: 'str(123)', points: 2, explanation: 'str() 函数。' },
  { id: 279, subject: 'python', type: 'single', title: '执行 print("a" + "b" * 2) 的结果是？', options: ['abab', 'abb', '报错', 'ab2'], answer: 'abb', points: 2, explanation: '乘法优先级高于加法。' },
  { id: 280, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2]\na.insert(0, 3)\nprint(a)', options: ['[1, 2, 3]', '[3, 1, 2]', '[1, 3, 2]', '报错'], answer: '[3, 1, 2]', points: 2, explanation: '在索引 0 处插入。' },
  { id: 281, subject: 'python', type: 'single', title: '如何获取列表 a 的长度？', options: ['a.size()', 'len(a)', 'a.length', 'count(a)'], answer: 'len(a)', points: 2, explanation: 'len()。' },
  { id: 282, subject: 'python', type: 'single', title: '执行 print(bool(1)) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '非零数字为 True。' },
  { id: 283, subject: 'python', type: 'single', title: '下列代码输出什么？\ndef func(x):\n    x = 10\na = 5\nfunc(a)\nprint(a)', options: ['5', '10', '报错', 'None'], answer: '5', points: 2, explanation: '不可变对象（整数）是传值。' },
  { id: 284, subject: 'python', type: 'single', title: '如何定义一个包含 1, 2, 3 的集合？', options: ['s = {1, 2, 3}', 's = [1, 2, 3]', 's = (1, 2, 3)', 's = "123"'], answer: 's = {1, 2, 3}', points: 2, explanation: '花括号且无键值对为集合。' },
  { id: 285, subject: 'python', type: 'single', title: '执行 print(set([1, 2, 2, 3])) 的结果是？', options: ['{1, 2, 2, 3}', '{1, 2, 3}', '[1, 2, 3]', '报错'], answer: '{1, 2, 3}', points: 2, explanation: '集合自动去重。' },
  { id: 286, subject: 'python', type: 'single', title: '下列代码输出什么？\nfor i in range(1, 1):\n    print(i)', options: ['1', '0', '什么都不输出', '报错'], answer: '什么都不输出', points: 2, explanation: '空范围。' },
  { id: 287, subject: 'python', type: 'single', title: '如何判断一个数 n 是否在列表 a 中？', options: ['n in a', 'a.contains(n)', 'n is a', 'n == a'], answer: 'n in a', points: 2, explanation: 'in 成员运算符。' },
  { id: 288, subject: 'python', type: 'single', title: '执行 print("abc".replace("a", "A")) 的结果是？', options: ['Abc', 'abc', 'ABC', '报错'], answer: 'Abc', points: 2, explanation: '替换。' },
  { id: 289, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2, 3]\nprint(a[0:3:2])', options: ['[1, 2, 3]', '[1, 3]', '[1, 2]', '[2]'], answer: '[1, 3]', points: 2, explanation: '步长为 2。' },
  { id: 290, subject: 'python', type: 'single', title: '如何将字符串 "123" 转换为列表 ["1", "2", "3"]？', options: ['list("123")', 'split("123")', 'str_to_list("123")', '报错'], answer: 'list("123")', points: 2, explanation: 'list() 迭代字符串。' },
  { id: 291, subject: 'python', type: 'single', title: '执行 print(10 ** 0) 的结果是？', options: ['10', '0', '1', '报错'], answer: '1', points: 2, explanation: '任何数的 0 次方为 1。' },
  { id: 292, subject: 'python', type: 'single', title: '下列代码输出什么？\nx = 10\ny = 5\nprint(x > y and x < 20)', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '逻辑与。' },
  { id: 293, subject: 'python', type: 'single', title: '如何定义一个匿名函数（lambda）？', options: ['lambda x: x*2', 'def(x): x*2', 'func x: x*2', 'anonymous x: x*2'], answer: 'lambda x: x*2', points: 2, explanation: 'lambda 关键字。' },
  { id: 294, subject: 'python', type: 'single', title: '执行 print(all([True, True, False])) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 2, explanation: 'all() 要求全部为真。' },
  { id: 295, subject: 'python', type: 'single', title: '执行 print(any([True, False, False])) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: 'any() 只要有一个为真。' },
  { id: 296, subject: 'python', type: 'single', title: '下列代码输出什么？\na = [1, 2]\nb = a\na = [3, 4]\nprint(b)', options: ['[1, 2]', '[3, 4]', '报错', 'None'], answer: '[1, 2]', points: 2, explanation: 'a 重新指向了新对象，b 仍指向旧对象。' },
  { id: 297, subject: 'python', type: 'single', title: '如何获取当前 Python 版本？', options: ['sys.version', 'os.version', 'python.version', 'version()'], answer: 'sys.version', points: 2, explanation: 'sys 模块。' },
  { id: 298, subject: 'python', type: 'single', title: '执行 print(" ".isspace()) 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 2, explanation: '检查是否为空格。' },
  { id: 299, subject: 'python', type: 'single', title: '下列代码输出什么？\nprint(1, 2, sep="-")', options: ['1 2', '1-2', '12', '报错'], answer: '1-2', points: 2, explanation: 'sep 指定分隔符。' },
  { id: 300, subject: 'python', type: 'single', title: 'YCL 4 级考试中，Python 的主要版本是？', options: ['Python 2', 'Python 3', 'Python 4', 'C++'], answer: 'Python 3', points: 2, explanation: '目前主流且考试使用的是 Python 3。' },

  // --- 判断题专项 (301-350) ---
  { id: 301, subject: 'python', type: 'single', title: 'Python 变量名可以以数字开头。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '变量名必须以字母或下划线开头。' },
  { id: 302, subject: 'python', type: 'single', title: 'Python 3 中，print 是一个函数。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'Python 3 中 print 变成了内置函数。' },
  { id: 303, subject: 'python', type: 'single', title: 'Python 代码块通过缩进来定义。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '缩进是 Python 语法的重要组成部分。' },
  { id: 304, subject: 'python', type: 'single', title: 'input() 函数返回的数据类型总是字符串。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '无论输入什么，input() 都将其作为字符串返回。' },
  { id: 305, subject: 'python', type: 'single', title: '在 Python 中，10 / 2 的结果是整数 5。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '结果是浮点数 5.0。' },
  { id: 306, subject: 'python', type: 'single', title: 'range(1, 5) 包含数字 5。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'range 的终点是不包含的。' },
  { id: 307, subject: 'python', type: 'single', title: '列表是不可变的数据类型。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '列表是可变的，元组才是不可变的。' },
  { id: 308, subject: 'python', type: 'single', title: 'Python 中，True 和 False 的首字母必须大写。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '布尔值是区分大小写的。' },
  { id: 309, subject: 'python', type: 'single', title: 'if 语句后面必须跟 else 语句。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'else 是可选的。' },
  { id: 310, subject: 'python', type: 'single', title: 'break 语句用于跳过本次循环，继续下一次。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'break 用于终止整个循环，continue 才是跳过本次。' },
  { id: 311, subject: 'python', type: 'single', title: 'Python 中，a = 10 和 a == 10 的意思是一样的。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '= 是赋值，== 是比较。' },
  { id: 312, subject: 'python', type: 'single', title: '字符串可以通过索引来修改其中的某个字符。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '字符串是不可变的。' },
  { id: 313, subject: 'python', type: 'single', title: 'len() 函数可以用来获取列表的长度。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'len() 适用于多种容器。' },
  { id: 314, subject: 'python', type: 'single', title: 'def 关键字用于定义一个类。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'def 用于定义函数，class 用于定义类。' },
  { id: 315, subject: 'python', type: 'single', title: '在函数内部定义的变量是局部变量。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '局部变量的作用域仅在函数内。' },
  { id: 316, subject: 'python', type: 'single', title: 'Python 支持多重继承。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'Python 允许一个类继承多个父类。' },
  { id: 317, subject: 'python', type: 'single', title: '10 % 3 的结果是 1。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '10 除以 3 余 1。' },
  { id: 318, subject: 'python', type: 'single', title: 'for 循环通常用于已知循环次数的情况。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'for 循环遍历序列。' },
  { id: 319, subject: 'python', type: 'single', title: 'while 循环只要条件为 True 就会一直执行。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '这是 while 循环的基本逻辑。' },
  { id: 320, subject: 'python', type: 'single', title: 'Python 中的注释以 // 开头。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '单行注释以 # 开头。' },
  { id: 321, subject: 'python', type: 'single', title: '字符串 "123" 可以直接和整数 1 相加。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '不同类型不能直接相加。' },
  { id: 322, subject: 'python', type: 'single', title: 'list.append() 方法在列表开头添加元素。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'append() 在末尾添加。' },
  { id: 323, subject: 'python', type: 'single', title: 'Python 中，0 的布尔值是 False。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '零值为假。' },
  { id: 324, subject: 'python', type: 'single', title: '空字符串 "" 的布尔值是 True。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '空字符串为假。' },
  { id: 325, subject: 'python', type: 'single', title: 'and 运算符要求两边都为 True 结果才为 True。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '逻辑与的定义。' },
  { id: 326, subject: 'python', type: 'single', title: 'or 运算符只要有一边为 True 结果就为 True。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '逻辑或的定义。' },
  { id: 327, subject: 'python', type: 'single', title: 'not 运算符用于对布尔值取反。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '逻辑非的定义。' },
  { id: 328, subject: 'python', type: 'single', title: 'range(10) 会生成 10 个数字。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '生成 0 到 9，共 10 个。' },
  { id: 329, subject: 'python', type: 'single', title: '在 Python 中，变量不需要声明类型。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'Python 是动态类型语言。' },
  { id: 330, subject: 'python', type: 'single', title: '元组定义后可以修改其中的元素。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '元组是不可变的。' },
  { id: 331, subject: 'python', type: 'single', title: '字典的键必须是唯一的。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '字典中不能有重复的键。' },
  { id: 332, subject: 'python', type: 'single', title: 'math.sqrt(16) 的结果是 4.0。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: 'sqrt 返回浮点数。' },
  { id: 333, subject: 'python', type: 'single', title: 'Python 中，所有函数都有返回值（默认为 None）。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '即使没有 return，也会返回 None。' },
  { id: 334, subject: 'python', type: 'single', title: '递归函数必须有一个终止条件。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '否则会导致无限递归。' },
  { id: 335, subject: 'python', type: 'single', title: '字符串 "abc" 的长度是 3。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '包含三个字符。' },
  { id: 336, subject: 'python', type: 'single', title: '列表 a = [1, 2, 3]，a[-1] 是 3。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '-1 索引指向最后一个。' },
  { id: 337, subject: 'python', type: 'single', title: 'Python 中，10 // 3 的结果是 3.33。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '// 是整除，结果是 3。' },
  { id: 338, subject: 'python', type: 'single', title: 'global 关键字用于在函数内声明全局变量。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '这样可以在函数内修改全局变量。' },
  { id: 339, subject: 'python', type: 'single', title: 'Python 3 中，range() 返回的是一个列表。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '返回的是一个 range 对象（迭代器）。' },
  { id: 340, subject: 'python', type: 'single', title: '字符串切片 s[1:3] 包含索引为 3 的字符。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: '切片是左闭右开的。' },
  { id: 341, subject: 'python', type: 'single', title: 'Python 中，None 等于 0。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'None 是独立的对象，不等于 0。' },
  { id: 342, subject: 'python', type: 'single', title: 'is 运算符用于判断两个对象是否是同一个。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '检查内存地址是否相同。' },
  { id: 343, subject: 'python', type: 'single', title: '== 运算符用于判断两个对象的值是否相等。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '检查内容是否相同。' },
  { id: 344, subject: 'python', type: 'single', title: 'Python 3 不支持中文变量名。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'Python 3 默认支持 Unicode，可以使用中文变量名。' },
  { id: 345, subject: 'python', type: 'single', title: 'lambda 表达式可以包含多行代码。', options: ['正确', '错误'], answer: '错误', points: 2, explanation: 'lambda 只能包含一个表达式。' },
  { id: 346, subject: 'python', type: 'single', title: '在 Python 中，所有对象都有布尔值。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '任何对象都可以用于条件判断。' },
  { id: 347, subject: 'python', type: 'single', title: '列表 a = [1, 2]，a * 3 的结果是 [1, 2, 1, 2, 1, 2]。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '列表重复。' },
  { id: 348, subject: 'python', type: 'single', title: 'Python 中的 pass 语句什么也不做。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '它是一个占位符。' },
  { id: 349, subject: 'python', type: 'single', title: 'YCL 4 级考试包含编程题。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '考试分为客观题和编程题。' },
  { id: 350, subject: 'python', type: 'single', title: '学习 Python 应该多动手写代码。', options: ['正确', '错误'], answer: '正确', points: 2, explanation: '实践出真知。' },
];




