import { Question } from './types';

export const QUESTION_BANK: Question[] = [
  // --- 原有题库 (1-100) ---
  { id: 1, type: 'single', title: 'Python 中用于输出的函数是？', options: ['print()', 'input()', 'len()', 'type()'], answer: 'print()', points: 5, explanation: 'print() 是 Python 的标准输出函数。' },
  { id: 2, type: 'single', title: 'Python 中用于接收输入的函数是？', options: ['print()', 'input()', 'len()', 'type()'], answer: 'input()', points: 5, explanation: 'input() 用于从键盘获取用户输入。' },
  { id: 3, type: 'single', title: '下列哪个符号用于表示 Python 的单行注释？', options: ['//', '/*', '#', '--'], answer: '#', points: 5, explanation: '# 符号后面的内容会被 Python 解释器忽略。' },
  { id: 4, type: 'single', title: '在 Python 中，a = 5, b = 3，那么 a + b 的值是？', options: ['8', '15', '2', '53'], answer: '8', points: 5, explanation: '执行数学加法运算。' },
  { id: 5, type: 'single', title: '下列哪个是合法的变量名？', options: ['1a', 'a-b', '_a', 'a b'], answer: '_a', points: 5, explanation: '变量名可以以下划线开头，但不能以数字开头，也不能包含空格或减号。' },
  { id: 6, type: 'single', title: '运行 print("Hello" + "World") 的结果是？', options: ['Hello World', 'HelloWorld', 'Hello+World', '报错'], answer: 'HelloWorld', points: 5, explanation: '字符串相加表示直接拼接。' },
  { id: 7, type: 'single', title: '在 Python 中，10 / 2 的结果类型是？', options: ['整数', '浮点数', '字符串', '布尔值'], answer: '浮点数', points: 5, explanation: 'Python 3 中的除法 / 总是返回浮点数。' },
  { id: 8, type: 'single', title: '运行 print(3 * 4) 的结果是？', options: ['7', '12', '34', '报错'], answer: '12', points: 5, explanation: '执行数学乘法运算。' },
  { id: 9, type: 'single', title: '在 Python 中，如何定义一个列表？', options: ['a = (1, 2)', 'a = [1, 2]', 'a = {1, 2}', 'a = "1, 2"'], answer: 'a = [1, 2]', points: 5, explanation: '列表使用方括号 [] 定义。' },
  { id: 10, type: 'single', title: '运行 print(10 % 3) 的结果是？', options: ['3', '1', '0', '0.33'], answer: '1', points: 5, explanation: '% 是取余运算符，10 除以 3 余 1。' },
  { id: 11, type: 'single', title: '在 Python 中，if 语句后面通常跟着什么符号？', options: [':', ';', '.', ','], answer: ':', points: 5, explanation: 'Python 使用冒号 : 来引导代码块。' },
  { id: 12, type: 'single', title: '运行 print(2 ** 3) 的结果是？', options: ['6', '8', '9', '5'], answer: '8', points: 5, explanation: '** 是幂运算符，2 的 3 次方是 8。' },
  { id: 13, type: 'single', title: '在 Python 中，如何获取字符串 "abc" 的长度？', options: ['len("abc")', '"abc".length()', 'size("abc")', 'count("abc")'], answer: 'len("abc")', points: 5, explanation: '使用内置函数 len()。' },
  { id: 14, type: 'single', title: '下列哪个是 Python 的比较运算符？', options: ['=', '==', ':=', '+='], answer: '==', points: 5, explanation: '== 用于判断两个值是否相等。' },
  { id: 15, type: 'single', title: '运行 print(int("123")) 的结果类型是？', options: ['字符串', '整数', '浮点数', '报错'], answer: '整数', points: 5, explanation: 'int() 函数将字符串转换为整数。' },
  { id: 16, type: 'single', title: '在 Python 中，for 循环常配合哪个函数使用？', options: ['range()', 'list()', 'print()', 'input()'], answer: 'range()', points: 5, explanation: 'range() 用于生成一系列数字。' },
  { id: 17, type: 'single', title: '运行 print(5 > 3) 的结果是？', options: ['True', 'False', '5', '3'], answer: 'True', points: 5, explanation: '5 大于 3 是正确的，所以返回 True。' },
  { id: 18, type: 'single', title: '在 Python 中，如何向列表 a 的末尾添加元素 10？', options: ['a.add(10)', 'a.append(10)', 'a.insert(10)', 'a.push(10)'], answer: 'a.append(10)', points: 5, explanation: 'append() 是列表添加元素的方法。' },
  { id: 19, type: 'single', title: '运行 print("Python"[0]) 的结果是？', options: ['P', 'y', 'n', '报错'], answer: 'P', points: 5, explanation: '索引 0 对应第一个字符。' },
  { id: 20, type: 'single', title: '在 Python 中，如何定义一个函数？', options: ['def my_func():', 'function my_func():', 'define my_func():', 'func my_func():'], answer: 'def my_func():', points: 5, explanation: '使用 def 关键字。' },
  { id: 21, type: 'single', title: '运行 print(bool(0)) 的结果是？', options: ['True', 'False', '0', '报错'], answer: 'False', points: 5, explanation: '在 Python 中，数字 0 的布尔值是 False。' },
  { id: 22, type: 'single', title: '在 Python 中，and 表示什么逻辑？', options: ['并且', '或者', '不是', '相等'], answer: '并且', points: 5, explanation: 'and 逻辑要求两边同时为真。' },
  { id: 23, type: 'single', title: '运行 print(10 // 3) 的结果是？', options: ['3', '3.33', '1', '0'], answer: '3', points: 5, explanation: '// 是整除运算符。' },
  { id: 24, type: 'single', title: '在 Python 中，如何将数字 10 转换为字符串？', options: ['str(10)', 'int(10)', 'string(10)', 'text(10)'], answer: 'str(10)', points: 5, explanation: '使用 str() 函数。' },
  { id: 25, type: 'single', title: '运行 print("a" * 3) 的结果是？', options: ['aaa', 'a3', '3a', '报错'], answer: 'aaa', points: 5, explanation: '字符串乘以数字表示重复。' },
  { id: 26, type: 'single', title: '在 Python 中，如何从列表 a 中删除第一个元素？', options: ['a.remove(0)', 'del a[0]', 'a.pop(0)', '以上都可以'], answer: '以上都可以', points: 5, explanation: 'del 和 pop(0) 都可以按索引删除，remove 是按值删除。' },
  { id: 27, type: 'single', title: '运行 print(type(1.5)) 的结果是？', options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", '报错'], answer: "<class 'float'>", points: 5, explanation: '1.5 是浮点数。' },
  { id: 28, type: 'single', title: '在 Python 中，elif 是什么意思？', options: ['否则', '如果', '否则如果', '循环'], answer: '否则如果', points: 5, explanation: 'elif 是 else if 的缩写。' },
  { id: 29, type: 'single', title: '运行 print(min(1, 2, 3)) 的结果是？', options: ['1', '2', '3', '报错'], answer: '1', points: 5, explanation: 'min() 返回最小值。' },
  { id: 30, type: 'single', title: '在 Python 中，如何导入 random 模块？', options: ['include random', 'import random', 'using random', 'require random'], answer: 'import random', points: 5, explanation: '使用 import 关键字。' },
  { id: 31, type: 'single', title: '运行 print(abs(-5)) 的结果是？', options: ['-5', '5', '0', '报错'], answer: '5', points: 5, explanation: 'abs() 返回绝对值。' },
  { id: 32, type: 'single', title: '在 Python 中，如何定义一个元组？', options: ['a = [1, 2]', 'a = (1, 2)', 'a = {1, 2}', 'a = "1, 2"'], answer: 'a = (1, 2)', points: 5, explanation: '元组使用圆括号 () 定义。' },
  { id: 33, type: 'single', title: '在 Python 中，or 表示什么逻辑？', options: ['并且', '或者', '不是', '相等'], answer: '或者', points: 5, explanation: 'or 逻辑只要两边有一个条件为真，结果就为真。' },
  { id: 34, type: 'single', title: '下列哪个是 Python 的循环语句？', options: ['if', 'while', 'else', 'elif'], answer: 'while', points: 5, explanation: 'while 语句用于在条件满足时重复执行一段代码。' },
  { id: 35, type: 'single', title: '想要提前跳出循环，可以使用哪个关键字？', options: ['continue', 'break', 'exit', 'stop'], answer: 'break', points: 5, explanation: 'break 关键字会立即终止当前循环，跳到循环外执行后面的代码。' },
  { id: 36, type: 'single', title: '运行 print(len([1, 2, 3])) 的结果是？', options: ['1', '2', '3', '4'], answer: '3', points: 5, explanation: 'len() 函数用于获取列表、字符串等对象的长度（元素个数）。' },
  { id: 37, type: 'single', title: '已知 s = "ABC"，那么 s[1] 是？', options: ['A', 'B', 'C', '报错'], answer: 'B', points: 5, explanation: '字符串也支持索引访问，从 0 开始，s[1] 是第二个字符 B。' },
  { id: 38, type: 'single', title: '运行 print(round(3.6)) 的结果是？', options: ['3', '4', '3.0', '4.0'], answer: '4', points: 5, explanation: 'round() 函数用于对浮点数进行四舍五入。' },
  { id: 39, type: 'single', title: '在 Python 中，如何定义一个空列表？', options: ['a = []', 'a = ()', 'a = {}', 'a = ""'], answer: 'a = []', points: 5, explanation: '空列表使用一对不含任何内容的方括号 [] 表示。' },
  { id: 40, type: 'single', title: '运行 print(5 // 2) 的结果是？', options: ['2', '2.5', '3', '0'], answer: '2', points: 5, explanation: '// 是整除运算符，5 除以 2 的商是 2。' },
  { id: 41, type: 'single', title: '在 Python 中，变量名区分大小写吗？', options: ['区分', '不区分', '看情况', '不一定'], answer: '区分', points: 5, explanation: 'Python 是区分大小写的语言，变量 a 和 A 是完全不同的。' },
  { id: 42, type: 'single', title: '运行 print(bool(1)) 的结果是？', options: ['True', 'False', '1', '报错'], answer: 'True', points: 5, explanation: '在 Python 中，非零数字转换为布尔值都是 True。' },
  { id: 43, type: 'single', title: '运行 print("apple" == "Apple") 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'False', points: 5, explanation: '因为区分大小写，小写 a 和大写 A 不同，所以这两个字符串不相等。' },
  { id: 44, type: 'single', title: '在 for 循环中，i 的值会自动变化吗？', options: ['会', '不会', '需要手动加1', '看情况'], answer: '会', points: 5, explanation: 'for 循环会自动遍历序列中的每一个元素，并将当前元素赋值给循环变量。' },
  { id: 45, type: 'single', title: '运行 a = [1, 2, 3]; print(a[1]) 的结果是？', options: ['1', '2', '3', '报错'], answer: '2', points: 5, explanation: '列表索引从 0 开始，a[1] 是第二个元素 2。' },
  { id: 46, type: 'single', title: '运行 print("a" in "apple") 的结果是？', options: ['True', 'False', '报错', 'None'], answer: 'True', points: 5, explanation: 'in 运算符用于检查一个字符串是否包含另一个字符串。' },
  { id: 47, type: 'single', title: '在 Python 中，如何给变量 a 赋值为 10？', options: ['a = 10', 'a == 10', '10 = a', 'a : 10'], answer: 'a = 10', points: 5, explanation: '使用单个等号 = 进行赋值操作。' },
  { id: 48, type: 'single', title: '运行 print(10 + 20) 的结果是？', options: ['1020', '30', '报错', '10+20'], answer: '30', points: 5, explanation: '两个整数相加，执行数学加法运算。' },
  { id: 49, type: 'single', title: '下列哪个是 Python 的开发环境？', options: ['IDLE', 'Word', 'Excel', 'PowerPoint'], answer: 'IDLE', points: 5, explanation: 'IDLE 是 Python 自带的集成开发和学习环境。' },
  { id: 50, type: 'single', title: '在 Python 中，elif 是什么意思？', options: ['否则如果', '如果', '否则', '循环'], answer: '否则如果', points: 5, explanation: 'elif 是 else if 的缩写，用于多分支判断。' },
  { id: 51, type: 'single', title: '运行 print(int(3.9)) 的结果是？', options: ['3', '4', '3.0', '报错'], answer: '3', points: 5, explanation: 'int() 转换浮点数时会直接舍弃小数部分，不进行四舍五入。' },
  { id: 52, type: 'single', title: '运行 print(2 + 3 * 4) 的结果是？', options: ['20', '14', '24', '9'], answer: '14', points: 5, explanation: '先算乘法 3 * 4 = 12，再算加法 2 + 12 = 14。' },
  { id: 53, type: 'single', title: '运行 print("Hello"[0]) 的结果是？', options: ['H', 'e', 'l', 'o'], answer: 'H', points: 5, explanation: '获取字符串的第一个字符，索引为 0。' },
  { id: 54, type: 'single', title: '在 Python 中，# 后面的内容会被执行吗？', options: ['会', '不会', '看情况', '只有第一行会'], answer: '不会', points: 5, explanation: '# 引导的是单行注释，解释器会忽略它。' },
  { id: 55, type: 'single', title: '运行 print(2 ** 3) 的结果是？', options: ['6', '8', '9', '5'], answer: '8', points: 5, explanation: '2 的 3 次方，即 2 * 2 * 2 = 8。' },
  { id: 56, type: 'single', title: '在 Python 中，如何获取列表 a 的长度？', options: ['a.length()', 'len(a)', 'a.size()', 'count(a)'], answer: 'len(a)', points: 5, explanation: '使用内置函数 len()。' },
  { id: 57, type: 'single', title: '运行 a = "Hello"; print(a.lower()) 的结果是？', options: ['HELLO', 'hello', 'Hello', '报错'], answer: 'hello', points: 5, explanation: 'lower() 方法将字符串中的所有大写字母转换为小写。' },
  { id: 58, type: 'single', title: '运行 print("123".isdigit()) 的结果是？', options: ['True', 'False', 'None', '报错'], answer: 'True', points: 5, explanation: 'isdigit() 检查字符串是否只由数字组成。' },
  { id: 59, type: 'single', title: '在 Python 中，如何定义一个函数？', options: ['function f():', 'def f():', 'define f():', 'func f():'], answer: 'def f():', points: 5, explanation: '使用关键字 def 来定义函数。' },
  { id: 60, type: 'single', title: '函数中使用哪个关键字返回结果？', options: ['get', 'return', 'back', 'give'], answer: 'return', points: 5, explanation: 'return 语句用于结束函数并将结果返回给调用者。' },
  { id: 61, type: 'single', title: '运行 print(min(5, 2, 8)) 的结果是？', options: ['5', '2', '8', '报错'], answer: '2', points: 5, explanation: 'min() 函数返回给定参数中的最小值。' },
  { id: 62, type: 'single', title: '运行 print(max(5, 2, 8)) 的结果是？', options: ['5', '2', '8', '报错'], answer: '8', points: 5, explanation: 'max() 函数返回给定参数中的最大值。' },
  { id: 63, type: 'single', title: '在 Python 中，如何导入数学模块 math？', options: ['include math', 'import math', 'using math', 'require math'], answer: 'import math', points: 5, explanation: '使用 import 关键字导入模块。' },
  { id: 64, type: 'single', title: '运行 a = [3, 1, 2]; a.sort(); print(a) 的结果是？', options: ['[3, 1, 2]', '[1, 2, 3]', '[3, 2, 1]', '报错'], answer: '[1, 2, 3]', points: 5, explanation: 'sort() 方法对列表进行原地升序排序。' },
  { id: 65, type: 'single', title: '运行 print(sum([1, 2, 3])) 的结果是？', options: ['3', '6', '123', '报错'], answer: '6', points: 5, explanation: 'sum() 函数对序列中的所有数值进行求和。' },
  { id: 66, type: 'single', title: '运行 print("Python"[:2]) 的结果是？', options: ['Py', 'yt', 'th', 'on'], answer: 'Py', points: 5, explanation: '切片操作 [:2] 表示从开头截取到索引 2 之前（不含 2），即索引 0 和 1。' },
  { id: 67, type: 'single', title: '运行 print(10 + True) 的结果是？', options: ['10', '11', 'True', '报错'], answer: '11', points: 5, explanation: '在 Python 中，True 在参与数学运算时被当作 1，False 被当作 0。' },
  { id: 68, type: 'single', title: '在 Python 中，如何定义一个元组？', options: ['a = []', 'a = ()', 'a = {}', 'a = ""'], answer: 'a = ()', points: 5, explanation: '元组使用圆括号 () 定义，且定义后不可修改。' },
  { id: 69, type: 'single', title: '在 Python 中，如何定义一个字典？', options: ['a = []', 'a = ()', 'a = {}', 'a = ""'], answer: 'a = {}', points: 5, explanation: '字典使用花括号 {} 定义，包含键值对。' },
  { id: 70, type: 'single', title: '运行 a = 10; a += 5; print(a) 的结果是？', options: ['10', '5', '15', '报错'], answer: '15', points: 5, explanation: 'a += 5 等同于 a = a + 5。' },
  { id: 71, type: 'multiple', title: '下列哪些是 Python 的基本数据类型？', options: ['int', 'str', 'float', 'list'], answer: ['int', 'str', 'float', 'list'], points: 5, explanation: '这些都是 Python 中最常用的基础数据类型。' },
  { id: 72, type: 'multiple', title: '下列哪些符号可以用于 Python 的注释？', options: ['#', '"""', "'''", '//'], answer: ['#', '"""', "'''"], points: 5, explanation: '# 用于单行注释，三引号用于多行注释。// 在 Python 中是整除运算符。' },
  { id: 73, type: 'multiple', title: '下列哪些是合法的变量名？', options: ['_a', 'a1', '1a', 'my_var'], answer: ['_a', 'a1', 'my_var'], points: 5, explanation: '变量名可以以下划线或字母开头，不能以数字开头。' },
  { id: 74, type: 'multiple', title: '下列哪些是 Python 的关键字？', options: ['if', 'else', 'elif', 'then'], answer: ['if', 'else', 'elif'], points: 5, explanation: 'Python 中没有 then 关键字，那是其他语言（如 Basic）的。' },
  { id: 75, type: 'multiple', title: '下列哪些运算符的结果是布尔值？', options: ['>', '==', '!=', '+'], answer: ['>', '==', '!='], points: 5, explanation: '比较运算符的结果都是 True 或 False。+ 是算术运算符。' },
  { id: 76, type: 'multiple', title: '下列哪些函数可以将其他类型转换为数字？', options: ['int()', 'float()', 'str()', 'bool()'], answer: ['int()', 'float()'], points: 5, explanation: 'int() 转整数，float() 转浮点数。str() 转字符串，bool() 转布尔值。' },
  { id: 77, type: 'multiple', title: '下列哪些是 Python 的循环结构？', options: ['for', 'while', 'do-while', 'repeat'], answer: ['for', 'while'], points: 5, explanation: 'Python 只有 for 和 while 两种循环。' },
  { id: 78, type: 'multiple', title: '下列哪些可以作为列表的元素？', options: ['数字', '字符串', '列表', '布尔值'], answer: ['数字', '字符串', '列表', '布尔值'], points: 5, explanation: 'Python 列表非常强大，可以容纳任何类型的对象。' },
  { id: 79, type: 'multiple', title: '下列哪些操作 can 改变列表的内容？', options: ['append()', 'pop()', 'insert()', 'len()'], answer: ['append()', 'pop()', 'insert()'], points: 5, explanation: '前三个都会修改列表，len() 只是获取长度，不修改内容。' },
  { id: 80, type: 'multiple', title: '下列哪些是 Python 的逻辑运算符？', options: ['and', 'or', 'not', 'xor'], answer: ['and', 'or', 'not'], points: 5, explanation: 'Python 原生逻辑运算符只有 and, or, not。' },
  { id: 81, type: 'multiple', title: '下列哪些是 Python 的算术运算符？', options: ['+', '-', '*', '/'], answer: ['+', '-', '*', '/'], points: 5, explanation: '这些都是基础的数学运算符号。' },
  { id: 82, type: 'multiple', title: '下列哪些是 Python 的比较运算符？', options: ['==', '!=', '<', '>'], answer: ['==', '!=', '<', '>'], points: 5, explanation: '这些用于比较两个值的大小或相等关系。' },
  { id: 83, type: 'multiple', title: '下列哪些是 Python 的赋值运算符？', options: ['=', '+=', '-=', '*='], answer: ['=', '+=', '-=', '*='], points: 5, explanation: '这些都用于给变量赋值或更新值。' },
  { id: 84, type: 'multiple', title: '下列哪些是 Python 的序列类型？', options: ['list', 'tuple', 'str', 'range'], answer: ['list', 'tuple', 'str', 'range'], points: 5, explanation: '序列类型支持索引、切片等操作。' },
  { id: 85, type: 'multiple', title: '下列哪些是 Python 的数值类型？', options: ['int', 'float', 'str', 'list'], answer: ['int', 'float'], points: 5, explanation: 'int 和 float 是数值，str 是文本，list 是容器。' },
  { id: 86, type: 'multiple', title: '下列哪些是 Python 的内置常量？', options: ['True', 'False', 'None', 'Null'], answer: ['True', 'False', 'None'], points: 5, explanation: 'Python 中没有 Null，对应的是 None。' },
  { id: 87, type: 'multiple', title: '下列哪些是 Python 的内置函数？', options: ['print()', 'input()', 'len()', 'type()'], answer: ['print()', 'input()', 'len()', 'type()'], points: 5, explanation: '这些都是 Python 启动时就自动加载的常用函数。' },
  { id: 88, type: 'multiple', title: '下列哪些是 Python 常用的标准库模块？', options: ['math', 'random', 'time', 'turtle'], answer: ['math', 'random', 'time', 'turtle'], points: 5, explanation: '这些是 YCL 4 级及基础学习中非常重要的模块。' },
  { id: 89, type: 'multiple', title: '下列哪些是 Python 的字符串方法？', options: ['upper()', 'lower()', 'strip()', 'split()'], answer: ['upper()', 'lower()', 'strip()', 'split()'], points: 5, explanation: '这些方法用于处理和转换文本字符串。' },
  { id: 90, type: 'multiple', title: '下列哪些是 Python 的列表方法？', options: ['append()', 'extend()', 'insert()', 'remove()'], answer: ['append()', 'extend()', 'insert()', 'remove()'], points: 5, explanation: '这些方法用于管理列表中的元素。' },
  { id: 91, type: 'multiple', title: '下列哪些是 Python 的字典方法？', options: ['get()', 'keys()', 'values()', 'items()'], answer: ['get()', 'keys()', 'values()', 'items()'], points: 5, explanation: '这些方法用于访问字典的键、值或项。' },
  { id: 92, type: 'multiple', title: '下列哪些是 Python 的控制流语句？', options: ['if', 'for', 'while', 'try'], answer: ['if', 'for', 'while', 'try'], points: 5, explanation: '这些语句控制程序的执行顺序 and 逻辑。' },
  { id: 93, type: 'multiple', title: '下列哪些是 Python 的异常处理关键字？', options: ['try', 'except', 'finally', 'else'], answer: ['try', 'except', 'finally', 'else'], points: 5, explanation: 'try-except 结构用于捕获和处理程序运行时的错误。' },
  { id: 94, type: 'multiple', title: '下列哪些是 Python 的导入关键字？', options: ['import', 'from', 'as', 'include'], answer: ['import', 'from', 'as'], points: 5, explanation: 'Python 使用 import, from, as 来管理模块导入。' },
  { id: 95, type: 'multiple', title: '下列哪些是 Python 的数值转换函数？', options: ['int()', 'float()', 'str()', 'bool()'], answer: ['int()', 'float()', 'str()', 'bool()'], points: 5, explanation: '这些函数用于在不同数据类型之间进行转换。' },
  { id: 96, type: 'multiple', title: '下列哪些是 Python 的序列操作函数？', options: ['len()', 'max()', 'min()', 'sum()'], answer: ['len()', 'max()', 'min()', 'sum()'], points: 5, explanation: '这些函数可以对列表、元组等序列进行统计计算。' },
  { id: 97, type: 'multiple', title: '下列哪些关于 Python 列表的描述是正确的？', options: ['列表使用方括号 []', '列表可以存储不同类型的数据', '列表的索引从 0 开始', '列表的大小是固定的'], answer: ['列表使用方括号 []', '列表可以存储不同类型的数据', '列表的索引从 0 开始'], points: 5, explanation: 'Python 列表是动态的，可以随时增加或删除元素，大小不固定。' },
  { id: 98, type: 'multiple', title: '下列哪些是 Python 中的比较运算符？', options: ['==', '!=', '>=', '<='], answer: ['==', '!=', '>=', '<='], points: 5, explanation: '这些符号用于比较两个值的大小或相等性。' },
  { id: 99, type: 'multiple', title: '下列哪些是 Python 中的逻辑运算符？', options: ['and', 'or', 'not', 'xor'], answer: ['and', 'or', 'not'], points: 5, explanation: 'Python 原生支持 and, or, not。' },
  { id: 100, type: 'multiple', title: '下列哪些是 Python 的文件操作模式？', options: ['"r"', '"w"', '"a"', '"rb"'], answer: ['"r"', '"w"', '"a"', '"rb"'], points: 5, explanation: 'r 是读，w 是写，a 是追加，rb 是以二进制格式读取。' },

  // --- 二、YCL 四级真题卷 (101-200) ---
  { id: 101, type: 'single', title: '在 Python 中，要在屏幕上显示文字，使用的命令是？', options: ['input', 'print', 'say', 'output'], answer: 'print', points: 1, explanation: 'print() 函数用于将内容输出到屏幕上。' },
  { id: 102, type: 'single', title: '想要让用户从键盘输入内容，使用的命令是？', options: ['print', 'input', 'enter', 'get'], answer: 'input', points: 1, explanation: 'input() 函数用于接收用户从键盘输入的内容。' },
  { id: 103, type: 'single', title: '执行语句 a = 10，变量 a 中存储的是？', options: ['字母 a', '数字 10', '等号', '空值'], answer: '数字 10', points: 1, explanation: '赋值语句 a = 10 将数字 10 存入变量 a 中。' },
  { id: 104, type: 'single', title: '下面哪个不可以作为变量名的开头？', options: ['字母', '下划线', '数字', '拼音'], answer: '数字', points: 1, explanation: 'Python 变量名不能以数字开头。' },
  { id: 105, type: 'single', title: 'print (3 + 5) 的运行结果是？', options: ['35', '8', '3+5', '报错'], answer: '8', points: 1, explanation: '3 + 5 是数学加法运算，结果为 8。' },
  { id: 106, type: 'single', title: 'print ("10" + "20") 的运行结果是？', options: ['30', '1020', '10+20', '报错'], answer: '1020', points: 1, explanation: '字符串相加表示拼接，"10" 和 "20" 拼接结果是 "1020"。' },
  { id: 107, type: 'single', title: '已知 a = 10，b = a，那么 b 的值是？', options: ['10', 'a', '0', '不确定'], answer: '10', points: 1, explanation: 'b = a 表示将 a 的值（10）赋给 b。' },
  { id: 108, type: 'single', title: '下面正确的赋值语句是？', options: ['5 = x', 'x == 5', 'x = 5', 'x + 5'], answer: 'x = 5', points: 1, explanation: '赋值使用单等号，且变量名必须在左侧。' },
  { id: 109, type: 'single', title: 'print (10 - 4) 的结果是？', options: ['6', '14', '41', '104'], answer: '6', points: 1, explanation: '10 减 4 等于 6。' },
  { id: 110, type: 'single', title: 'print (3 * 6) 的结果是？', options: ['9', '18', '36', '63'], answer: '18', points: 1, explanation: '3 乘以 6 等于 18。' },
  { id: 111, type: 'single', title: 'Python 中表示 8 除以 2 的是？', options: ['8\\2', '8/2', '8÷2', '8%2'], answer: '8/2', points: 1, explanation: 'Python 使用斜杠 / 表示除法。' },
  { id: 112, type: 'single', title: '9 // 2 的计算结果是？', options: ['4', '4.5', '5', '1'], answer: '4', points: 1, explanation: '// 是整除运算符，9 除以 2 的商是 4。' },
  { id: 113, type: 'single', title: '7 % 2 是求余数，结果是？', options: ['3', '1  ', '0', '7'], answer: '1', points: 1, explanation: '% 是取余运算符，7 除以 2 余数是 1。' },
  { id: 114, type: 'single', title: '10 % 3 的余数是？', options: ['0', '1', '2', '3'], answer: '1', points: 1, explanation: '10 除以 3 的余数是 1。' },
  { id: 115, type: 'single', title: '执行 a = 2，再执行 a = a + 3，a 的值是？', options: ['2', '3', '5', '6'], answer: '5', points: 1, explanation: 'a 原本是 2，加 3 后变为 5。' },
  { id: 116, type: 'single', title: '4 + 6 * 2 的运算结果是？', options: ['20', '16', '10', '12'], answer: '16', points: 1, explanation: '先算乘法 6 * 2 = 12，再算加法 4 + 12 = 16。' },
  { id: 117, type: 'single', title: '(4 + 6) * 2 的运算结果是？', options: ['16', '20', '10', '12'], answer: '20', points: 1, explanation: '先算括号内 4 + 6 = 10，再算 10 * 2 = 20。' },
  { id: 118, type: 'single', title: '下面哪个算式结果等于 0？', options: ['5%2', '6%3', '7%2', '9%4'], answer: '6%3', points: 1, explanation: '6 能被 3 整除，余数为 0。' },
  { id: 119, type: 'single', title: '执行 a = 10，a += 2，a 的值是？', options: ['10', '2', '12', '20'], answer: '12', points: 1, explanation: 'a += 2 等效于 a = a + 2，即 10 + 2 = 12。' },
  { id: 120, type: 'single', title: '执行 a = 8，a -= 3，a 的值是？', options: ['5', '3', '8', '11'], answer: '5', points: 1, explanation: 'a -= 3 等效于 a = a - 3，即 8 - 3 = 5。' },
  { id: 121, type: 'single', title: 'Python 中表示 “等于” 的符号是？', options: ['=', '==', '!=', '<>'], answer: '==', points: 1, explanation: '双等号 == 用于判断两个值是否相等。' },
  { id: 122, type: 'single', title: 'Python 中表示 “不等于” 的符号是？', options: ['==', '=', '!=', '=>'], answer: '!=', points: 1, explanation: '!= 用于判断两个值是否不相等。' },
  { id: 123, type: 'single', title: '判断 3 > 5 的结果是？', options: ['True', 'False', '3', '5'], answer: 'False', points: 1, explanation: '3 不大于 5，所以结果为假（False）。' },
  { id: 124, type: 'single', title: '判断 5 >= 5 的结果是？', options: ['True', 'False', '5', '10'], answer: 'True', points: 1, explanation: '5 等于 5，满足大于等于条件，结果为真（True）。' },
  { id: 125, type: 'single', title: '运行下面程序，输出结果是？\na = 8\nif a > 5:\n    print ("大")\nelse:\n    print ("小")', options: ['大', '小', '8', '5'], answer: '大', points: 1, explanation: 'a 为 8，满足 a > 5，执行 if 分支打印“大”。' },
  { id: 126, type: 'single', title: '判断一个数 n 是偶数的条件是？', options: ['n%2==0', 'n%2==1', 'n/2==0', 'n*2==0'], answer: 'n%2==0', points: 1, explanation: '偶数除以 2 的余数一定为 0。' },
  { id: 127, type: 'single', title: '判断一个数 n 是奇数的条件是？', options: ['n%2==0', 'n%2==1', 'n==2', 'n>2'], answer: 'n%2==1', points: 1, explanation: '奇数除以 2 的余数一定为 1。' },
  { id: 128, type: 'single', title: 'if 10 > 20: 下方的代码会执行吗？', options: ['会', '不会', '不一定', '报错'], answer: '不会', points: 1, explanation: '10 > 20 为假，if 块内的代码不会被执行。' },
  { id: 129, type: 'single', title: '多条件判断使用的关键字是？', options: ['else', 'elif', 'ifs', 'and'], answer: 'elif', points: 1, explanation: 'elif 用于在 if 之后添加额外的条件判断。' },
  { id: 130, type: 'single', title: '表示 “并且” 关系的逻辑词是？', options: ['or', 'and', 'not', 'if'], answer: 'and', points: 1, explanation: 'and 要求两边的条件同时成立。' },
  { id: 131, type: 'single', title: 'for i in range (5): 会循环几次？', options: ['4', '5', '6', '无数次'], answer: '5', points: 1, explanation: 'range(5) 生成 0, 1, 2, 3, 4，共 5 个数字。' },
  { id: 132, type: 'single', title: 'range (1,5) 包含的数字是？', options: ['1,2,3,4', '1,2,3,4,5', '0,1,2,3,4', '5'], answer: '1,2,3,4', points: 1, explanation: 'range(start, end) 包含 start 但不包含 end。' },
  { id: 133, type: 'single', title: 'range (1,10,2) 生成的数字是？', options: ['1,3,5,7,9', '2,4,6,8,10', '1 到 10', '1 到 9'], answer: '1,3,5,7,9', points: 1, explanation: '从 1 开始，步长为 2，生成 1, 3, 5, 7, 9。' },
  { id: 134, type: 'single', title: '想要循环打印 1～10，应使用？', options: ['range (10)', 'range (1,10)', 'range (1,11)', 'range (0,10)'], answer: 'range (1,11)', points: 1, explanation: 'range(1, 11) 生成 1 到 10。' },
  { id: 135, type: 'single', title: '运行下面程序，s 的最终值是？\ns = 0\nfor i in range (1,4):\n    s = s + i', options: ['3', '4', '6', '10'], answer: '6', points: 1, explanation: 'i 依次为 1, 2, 3，累加结果为 1+2+3=6。' },
  { id: 136, type: 'single', title: '循环中，想要立刻跳出整个循环用？', options: ['continue', 'break', 'stop', 'end'], answer: 'break', points: 1, explanation: 'break 用于立即终止循环。' },
  { id: 137, type: 'single', title: '循环中，跳过本次，直接进入下一次用？', options: ['break', 'continue', 'pass', 'skip'], answer: 'continue', points: 1, explanation: 'continue 用于跳过当前循环的剩余部分，开始下一次循环。' },
  { id: 138, type: 'single', title: 'for c in "abc": 会循环几次？', options: ['0', '1', '2', '3'], answer: '3', points: 1, explanation: '字符串 "abc" 有 3 个字符，循环 3 次。' },
  { id: 139, type: 'single', title: '打印 5 个星号 *，最简单的是？', options: ['print ("*" * 5)', 'print(5)', 'print(*5)', 'print(5)'], answer: 'print ("*" * 5)', points: 1, explanation: '字符串乘法 "*" * 5 会生成 "*****"。' },
  { id: 140, type: 'single', title: '求 1+2+…+10，循环中正确写法是？', options: ['s = i', 's += i', 's = 10', 'i += s'], answer: 's += i', points: 1, explanation: 's += i 用于将当前的 i 累加到 s 中。' },
  { id: 141, type: 'single', title: '"hello" 是什么数据类型？', options: ['整数', '字符串', '列表', '小数'], answer: '字符串', points: 1, explanation: '用引号括起来的内容是字符串（str）。' },
  { id: 142, type: 'single', title: '获取字符串长度的函数是？', options: ['len ()', 'length ()', 'size ()', 'count ()'], answer: 'len ()', points: 1, explanation: 'len() 函数返回对象的长度。' },
  { id: 143, type: 'single', title: 's = "python"，s [0] 表示第 1 个字符，是？', options: ['p', 'y', 't', 'h'], answer: 'p', points: 1, explanation: 'Python 索引从 0 开始，第一个字符是 p。' },
  { id: 144, type: 'single', title: 'Python 中列表使用的符号是？', options: ['()', '[]', '{}', '""'], answer: '[]', points: 1, explanation: '列表（list）使用方括号 [] 定义。' },
  { id: 145, type: 'single', title: 'lst = [1,2,3]，lst [1] 的值是？', options: ['1', '2', '3', '0'], answer: '2', points: 1, explanation: '索引 1 是列表中的第二个元素，即 2。' },
  { id: 146, type: 'single', title: '给列表末尾添加一个元素用？', options: ['add', 'append', 'insert', 'put'], answer: 'append', points: 1, explanation: 'append() 方法用于在列表末尾添加元素。' },
  { id: 147, type: 'single', title: 'lst = [10,20,30]，列表长度是？', options: ['2', '3', '10', '60'], answer: '3', points: 1, explanation: '列表中有 3 个元素，长度为 3。' },
  { id: 148, type: 'single', title: '下面表示空列表的是？', options: ['[]', '{}', '()', '""'], answer: '[]', points: 1, explanation: '[] 表示不含任何元素的列表。' },
  { id: 149, type: 'single', title: '把字符串 "123" 变成整数用？', options: ['int ()', 'str ()', 'float ()', 'num ()'], answer: 'int ()', points: 1, explanation: 'int() 函数将内容转换为整数。' },
  { id: 150, type: 'single', title: '把数字 123 变成字符串用？', options: ['str (123)', 'int (123)', 'string (123)', 'text (123)'], answer: 'str (123)', points: 1, explanation: 'str() 函数将内容转换为字符串。' },
  { id: 151, type: 'single', title: '定义函数使用的关键字是？', options: ['function', 'def', 'func', 'define'], answer: 'def', points: 1, explanation: 'def 是 define 的缩写，用于定义函数。' },
  { id: 152, type: 'single', title: '函数中返回结果用的关键字是？', options: ['back', 'return', 'give', 'out'], answer: 'return', points: 1, explanation: 'return 用于从函数中返回一个值。' },
  { id: 153, type: 'single', title: '函数可以没有参数吗？', options: ['可以', '不可以', '必须 1 个', '必须多个'], answer: '可以', points: 1, explanation: '函数可以不接收任何参数。' },
  { id: 154, type: 'single', title: '递归函数是指？', options: ['函数里有循环', '函数调用自己', '函数没有名字', '函数只打印内容'], answer: '函数调用自己', points: 1, explanation: '递归是指函数在内部调用自身的编程技巧。' },
  { id: 155, type: 'single', title: '求 1 到 n 的所有数相加，这种算法叫？', options: ['查找', '累加', '排序', '取余'], answer: '累加', points: 1, explanation: '累加是指将一系列数值不断加到总和中。' },
  { id: 156, type: 'single', title: '把所有可能一个个试一遍找答案叫？', options: ['枚举', '递归', '冒泡', '随机'], answer: '枚举', points: 1, explanation: '枚举法（穷举法）是列出所有可能情况进行验证。' },
  { id: 157, type: 'single', title: '下面对质数描述正确的是？', options: ['大于 1，只能被 1 和自己整除', '能被 2 整除', '一定是奇数', '一定是偶数'], answer: '大于 1，只能被 1 和自己整除', points: 1, explanation: '质数（素数）的定义是只有 1 和它本身两个因数的自然数。' },
  { id: 158, type: 'single', title: '下面哪个数是质数？', options: ['4', '6', '7', '9'], answer: '7', points: 1, explanation: '7 只能被 1 和 7 整除。' },
  { id: 159, type: 'single', title: '下面哪个是正确的闰年判断条件？', options: ['能被 4 整除就是闰年', '能被 100 整除就是闰年', '能被 4 整除但不能被 100 整除，或能被 400 整除', '能被 2 整除就是闰年'], answer: '能被 4 整除但不能被 100 整除，或能被 400 整除', points: 1, explanation: '这是公历闰年的标准判断规则。' },
  { id: 160, type: 'single', title: '想让程序重复做一件事，最好用？', options: ['判断', '循环', '函数', '字符串'], answer: '循环', points: 1, explanation: '循环结构专门用于处理重复性任务。' },
  { id: 161, type: 'single', title: 'print 命令的作用是在屏幕上输出内容。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，print 是 Python 的输出函数。' },
  { id: 162, type: 'single', title: 'input 获取的内容默认是数字类型。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，input() 获取的内容默认为字符串类型。' },
  { id: 163, type: 'single', title: 'Python 的变量名可以使用中文。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，Python 3 支持 Unicode，可以使用中文作为变量名（但不推荐）。' },
  { id: 164, type: 'single', title: '赋值符号 = 和等于符号 == 作用一样。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，= 是赋值，== 是判断相等。' },
  { id: 165, type: 'single', title: '5 > 10 的结果是 True。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，5 不大于 10，结果应为 False。' },
  { id: 166, type: 'single', title: 'if 语句的末尾必须加上冒号。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，冒号用于引导代码块。' },
  { id: 167, type: 'single', title: 'for 循环可以让一段代码重复执行。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，这是循环的基本功能。' },
  { id: 168, type: 'single', title: 'range (3) 生成的数字是 0、1、2。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，range(n) 生成 0 到 n-1。' },
  { id: 169, type: 'single', title: 'break 语句可以跳出当前循环。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，break 用于终止循环。' },
  { id: 170, type: 'single', title: 'continue 语句会直接结束整个循环。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，continue 只结束本次循环，break 才是结束整个循环。' },
  { id: 171, type: 'single', title: '列表里可以同时存放数字和字符串。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，Python 列表可以容纳混合类型的元素。' },
  { id: 172, type: 'single', title: '列表的下标（索引）是从 1 开始数的。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，Python 索引从 0 开始。' },
  { id: 173, type: 'single', title: 'len ("abc") 的运行结果是 3。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，"abc" 包含 3 个字符。' },
  { id: 174, type: 'single', title: ' "abc" + "123" 的结果是 "abc123"。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，字符串加法执行拼接操作。' },
  { id: 175, type: 'single', title: '每一个函数都必须 write return。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，函数可以没有返回值，默认返回 None。' },
  { id: 176, type: 'single', title: '1 + "1" 在 Python 中运行会报错。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，整数和字符串不能直接相加。' },
  { id: 177, type: 'single', title: '所有奇数除以 2 的余数都是 1。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，这是奇数的数学特性。' },
  { id: 178, type: 'single', title: '数字 0 是偶数。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，0 能被 2 整除。' },
  { id: 179, type: 'single', title: '递归函数必须要有结束的条件。', options: ['√', '×'], answer: '√', points: 1, explanation: '正确，否则会导致无限递归（死循环）。' },
  { id: 180, type: 'single', title: 'Python 里只能写英文，不能写中文注释。', options: ['√', '×'], answer: '×', points: 1, explanation: '错误，Python 支持中文注释。' },
  { id: 181, type: 'programming', title: '编写代码，打印输出：我爱 Python', answer: 'print("我爱 Python")', points: 1, explanation: '使用 print() 函数输出指定的字符串。' },
  { id: 182, type: 'programming', title: '输入一个名字，输出：你好，XX', answer: 'name = input()\nprint("你好，" + name)', points: 1, explanation: '使用 input() 获取输入，并用 + 进行字符串拼接。' },
  { id: 183, type: 'programming', title: '输入两个整数，输出它们的和', answer: 'a = int(input())\nb = int(input())\nprint(a + b)', points: 1, explanation: '输入后需用 int() 转换为整数再相加。' },
  { id: 184, type: 'programming', title: '输入一个数，判断它是不是正数', answer: 'n = int(input())\nif n > 0:\n    print("是正数")\nelse:\n    print("不是正数")', points: 1, explanation: '正数是指大于 0 的数。' },
  { id: 185, type: 'programming', title: '输入一个数，判断它是奇数还是偶数', answer: 'n = int(input())\nif n % 2 == 0:\n    print("偶数")\nelse:\n    print("奇数")', points: 1, explanation: '通过对 2 取余来判断奇偶性。' },
  { id: 186, type: 'programming', title: '打印 1 到 10 的所有数字', answer: 'for i in range(1, 11):\n    print(i)', points: 1, explanation: 'range(1, 11) 生成 1 到 10。' },
  { id: 187, type: 'programming', title: '计算 1 到 10 的和，并输出结果', answer: 's = 0\nfor i in range(1, 11):\n    s += i\nprint(s)', points: 1, explanation: '使用循环进行累加。' },
  { id: 188, type: 'programming', title: '打印 100 以内的所有偶数', answer: 'for i in range(0, 101, 2):\n    print(i)', points: 1, explanation: '使用步长为 2 的 range 函数。' },
  { id: 189, type: 'programming', title: '输入一个数字 n，打印 n 个星号 *', answer: 'n = int(input())\nprint("*" * n)', points: 1, explanation: '字符串乘法可以快速重复字符。' },
  { id: 190, type: 'programming', title: '输入一个字符串，输出它的长度', answer: 's = input()\nprint(len(s))', points: 1, explanation: '使用 len() 函数获取长度。' },
  { id: 191, type: 'programming', title: '输入一个字符串，将它逆序输出', answer: 's = input()\nprint(s[::-1])', points: 1, explanation: '使用切片 [::-1] 实现逆序。' },
  { id: 192, type: 'programming', title: '创建列表 [1,2,3,4,5]，输出第 3 个数', answer: 'lst = [1, 2, 3, 4, 5]\nprint(lst[2])', points: 1, explanation: '索引 2 对应第三个元素。' },
  { id: 193, type: 'programming', title: '已有列表 [1,2,3]，添加数字 10 后输出整个列表', answer: 'lst = [1, 2, 3]\nlst.append(10)\nprint(lst)', points: 1, explanation: '使用 append() 方法添加元素。' },
  { id: 194, type: 'programming', title: '定义一个函数，调用后输出：欢迎学习编程', answer: 'def hello():\n    print("欢迎学习编程")\nhello()', points: 1, explanation: '定义函数后记得调用它。' },
  { id: 195, type: 'programming', title: '定义一个函数，接收两个数，返回它们的和', answer: 'def add(a, b):\n    return a + b\nprint(add(3, 5))', points: 1, explanation: '使用 return 返回计算结果。' },
  { id: 196, type: 'programming', title: '输入一个年份，判断是闰年还是平年', answer: 'year = int(input())\nif (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:\n    print("闰年")\nelse:\n    print("平年")', points: 1, explanation: '闰年的判断逻辑需要包含百年不闰但四百年再闰的规则。' },
  { id: 197, type: 'programming', title: '找出 1～20 之间的所有质数并打印', answer: 'for n in range(2, 21):\n    flag = True\n    for i in range(2, n):\n        if n % i == 0:\n            flag = False\n            break\n    if flag:\n        print(n)', points: 1, explanation: '使用嵌套循环检查每个数是否为质数。' },
  { id: 198, type: 'programming', title: '输入一个数，判断它是不是质数', answer: 'n = int(input())\nis_prime = True\nfor i in range(2, n):\n    if n % i == 0:\n        is_prime = False\n        break\nif is_prime and n > 1:\n    print("是质数")\nelse:\n    print("不是质数")', points: 1, explanation: '质数必须大于 1 且只能被 1 和自身整除。' },
  { id: 199, type: 'programming', title: '打印九九乘法表的前 5 行', answer: 'for i in range(1, 6):\n    for j in range(1, i + 1):\n        print(j, "*", i, "=", i * j, end="  ")\n    print()', points: 1, explanation: '使用嵌套循环，内层循环控制列，外层控制行。' },
  { id: 200, type: 'programming', title: '输入一个字符串，判断它是不是回文（正读反读一样）', answer: 's = input()\nif s == s[::-1]:\n    print("是回文")\nelse:\n    print("不是回文")', points: 1, explanation: '比较原字符串和逆序字符串是否相等。' },
];
